Add simple POWGEN workflow
scipp/ess-legacy-v2 pull request #113
Opened 2022-02-28 13:43 UTC by jl-wynen

2022-02-28 13:45 UTC, SimonHeybrock commented on docs/index.rst
> +   instruments/powgen/powgen
I don't think we should add "top level" instrument submodules for instruments that are not at least related to ESS work?

2022-02-28 13:47 UTC, jl-wynen commented on docs/index.rst
> +   instruments/powgen/powgen
What about amor?
I was thinking of removing that module once we have something for DREAM. So it wouldn't be a big issue, I think.

2022-02-28 13:49 UTC, SimonHeybrock commented on docs/index.rst
> +   instruments/powgen/powgen
AMOR is closely related to ESTIA (using very similar detector technology, same scientists, used for testing ESS hardware, ...).

2022-03-01 14:35 UTC, SimonHeybrock reviewed
Not done yet with review, comments for first part (excluding notebooks).

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +        return (tof - tzero) / difc
Could write this with one fewer allocation?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +    tof_data = data.transform_coords('tof', graph={}, quiet=True)
This is to turn this into a coord?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
Any reason for this, apart from saving memory?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    out.masks['cal'] = calibration['mask'].data
May silently remove an existing `cal` mask.

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    if not sc.identical(into.coords[dim], calibration.coords[dim]):
What is this coord? Pixel IDs?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +            out.attrs[name] = out.coords.pop(name)
Why is this necessary? Isn't this what we tried to avoid by carefully designing `transform_coords`?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +        return fn(sc.concat([fn(edge[dim, index]) for edge in edges], aux_dim), aux_dim)
Looking for https://scipp.github.io/generated/functions/scipp.reduce.html#scipp.reduce?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    hi = extremum(sc.max, 1)
Is the 1 intentional, or should it be -1?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +        empty_instr.attrs['tof'] = tof_edges
An awful lot of code... can this somehow be ensured by applying the same workflow to both data and empty instrument before calling this? Is there a practical use for different edges?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    if 'wavelength' not in mon.coords:
Is the `if` required?

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +        mon = sc.rebin(mon, 'wavelength', wavelength_edges)
Can probably worry about this later, but monitors can (and will) be event mode.

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    return data / proton_charge
Is this the way we want to go? This function does extremely little, but requires a lot of code.

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    return sc.histogram(out, bins=edges)
Why does normalization histogram? The user may want to normalize but not histogram yet.

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/grouping.py
> +        data.coords['two_theta'] = scn.two_theta(data)
Have you considered using `transform_coords` (or the diffraction-specific helper functions you implement above) to compute this? Avoids the `if` and reliance on (the possibly soon legacy) `scn.two_theta`.

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +                  advanced_geometry=True,
Note that this option can be very slow. Is it needed for getting detector IDs? If not we should try to avoid it.

2022-03-01 14:35 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +
Personal bookmark (ignore this)

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    limit = da.meta['gd_prtn_chrg'].to(unit=charge.unit)
Very specific names hard coded in generic diffraction module?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +        return vanadium
This should not be in the `diffraction` module.

Filtering by proton charge is simple, what stops us from doing it now?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    return subtract_empty_instrument(vanadium, empty_instrument)
Coming back to my question on this function (above): Just switching out the edges to cover the union of the intervals seems like it can go badly wrong. If either of vanadium or empty instrument do not cover the full wavelength range then maybe there is a reason for this?

Furthermore, as soon as someone introduces additional binning, e.g., to mask a tof or wavelength range this seems like it may break very easily.

Can we find a mechanism that deals with imposing common wavelength (or TOF) binning "upstream" rather than attempting to fix it here?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    return var.to(dtype=bool)
Is this for dealing with Mantid's bin masks?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +        Name of the instrument.
Is this the route ESS wants to take? I thought scicat would deal with this? This seems to be replicating a Mantid-like interface, with its drawbacks such as multiple mutually exclusive options, ...?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/smoothing.py
> +def fft_smooth(da: sc.DataArray,
I'd stick with the naming of scipy rather than Mantid?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/diffraction/smoothing.py
> +    See :py:func:`scipp.signal.butter` for information on filter design.
Mention that this uses the midpoints?

2022-03-02 08:00 UTC, SimonHeybrock commented on src/ess/external/powgen/beamline.py
> +    # detector_info contains spectrum indices which start at 0.
This is unfortunately not sufficient. Spectrum indices are from 0 to N-1, but spectrum numbers are arbitrary. We can, for example, load only a single bank, or a bank may be disabled.

2022-03-02 15:05 UTC, jl-wynen commented on src/ess/external/powgen/beamline.py
> +    # detector_info contains spectrum indices which start at 0.
How is this represented in the inputs? Does `detector_info` change?

Do we even need to convert to spectrum for diffraction at ESS? We could just stay in 'detector', no?

2022-03-02 15:09 UTC, SimonHeybrock commented on src/ess/external/powgen/beamline.py
> +    # detector_info contains spectrum indices which start at 0.
`detector_info` would be the same. In Mantid each spectrum has a set of associated detectors, so I think it gets looked up via that.

Currently I do not think that ESS would/should operate in this manner.

2022-03-02 15:09 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +    if not sc.identical(into.coords[dim], calibration.coords[dim]):
spectrum

2022-03-02 15:10 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +    out.masks['cal'] = calibration['mask'].data
It might also overwrite the other attrs. What do you suggest? Raise an exception if something with the same name already exists?

2022-03-02 15:46 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +        empty_instr.attrs['tof'] = tof_edges
The min and max tof values are different for vanadium and empty instrument. And therefore, the wavelengths. I don't think we can enforce the same edges.

But as we discussed, this all goes away if we don't have tof edges in the first place.

2022-03-02 15:50 UTC, jl-wynen commented on src/ess/diffraction/grouping.py
> +        data.coords['two_theta'] = scn.two_theta(data)
This would potentially turn the position coords into attrs. But that is probably desirable because we process the position information here anyway. (And in practice, it does not matter because this function is applied to d-spacing...) Changing

2022-03-02 15:57 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +        return (tof - tzero) / difc
Done for the actual computation.
Is there a way to avoid the temporary array in `sc.all`?

2022-03-02 15:59 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
No. We could also preserve it as an attr. But in my tests with WISH data, I sometimes got quite close to the limits of my machine, so removing a spectrum x tof - sized coord can be relevant.

2022-03-02 15:59 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +    tof_data = data.transform_coords('tof', graph={}, quiet=True)
Yes

2022-03-02 16:01 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +            out.attrs[name] = out.coords.pop(name)
They are not used by the transformation. We could make them dummy inputs but then, we would require them to exist.

2022-03-02 16:03 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +    if 'wavelength' not in mon.coords:
I wanted to give the option to not rebin.

This whole function is kind of untested because it is not needed for POWGEN. So I am a bit unsure about the requirements. But since I had already written / copied it for WISH, I kept it.

2022-03-02 16:04 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +    return data / proton_charge
What do you mean? A lot of code to call? Or a lot of code because of the option to do it in-place?

I am suspecting that this function will become more complicated, depending on if the proton charge is precomputed.

2022-03-02 16:05 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +    return sc.histogram(out, bins=edges)
To ensure that the data and vanadium use the same edges. Or is it fine if they are different?

2022-03-03 07:45 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
Would it be useful if the conversion to d-spacing (with calibration) on consumed (and removed) those coords?

2022-03-03 07:46 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    out.masks['cal'] = calibration['mask'].data
Not sure. Probably?

2022-03-03 07:48 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +        return (tof - tzero) / difc
> Is there a way to avoid the temporary array in sc.all?

That is just one value per pixel, i.e., tiny and irrelevant?

> Done for the actual computation.

You mean for the `else` branch? But don't we frequently hit this branch in practice as well?

2022-03-03 07:49 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +            out.attrs[name] = out.coords.pop(name)
... but we have to remove them do avoid them interfering later?

2022-03-03 07:50 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +        empty_instr.attrs['tof'] = tof_edges
> The min and max tof values are different for vanadium and empty instrument. And therefore, the wavelengths. I don't think we can enforce the same edges.

But isn't this simply due to how we "guess" a good default value for the TOF bounds when loading data? If you impose common TOF edges from that start then at least you do not need to modify wavelength as well?

2022-03-03 07:55 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    return data / proton_charge
I think my question is whether it was worth having it as a function (or whether it should just be done directly within a higher-level function), and having to worry about signatures (such as in-place options).

2022-03-03 07:57 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    return sc.histogram(out, bins=edges)
Well, you normalized in event-mode. So you question is whether it is fine to later pick a binning different from the normalization-term binning for the normalized data?

I *think* that is fine, and possibly done frequently -- think also of other normalization terms such as monitor or direct-beam (SANS). These terms may vary smoothly and the concrete binning may be very different.

2022-03-03 07:59 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +        return (tof - tzero) / difc
No, I pushed a change for the then branch.

2022-03-03 08:07 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
This is rather tricky. We would have to use two transforms:
```.py
aux = tof_data.transform_coords('aux', graph={'aux': 'tof'}, keep_inputs=False)
aux.transform_coords('tof', graph={'tof': lambda aux, wavelength: aux}, keep_inputs=False)
```
We cannot simply use 
```.py
tof_data.transform_coords('tof', graph={'tof': lambda tof, wavelength: tof}, keep_inputs=False)
```
because that would not hit the node in the graph, it would simply promote `tof` to a coord and leave `wavelength` untouched (including the wavelength dim).

2022-03-03 15:44 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
Regarding handling wavelength and the positions via `transform_coords`:

We can add nodes to the graph to consume them in addition to the calibration parameters, or modify the existing node. But this would make those coords mandatory. (I experimented a bit with adding arguments to function signatures dynamically. It is possible but quite involved.)
I don't think that positions should be mandatory, users might want to not even load them if they do everything in terms of calibration parameters (e.g. in autoreduction).

We could probably pull off some shenanigans by calling `transform_coords` multiple times. But I doubt that it would make the code (or log messages) easier to understand than the current implementation.
Do you have any suggestions?

2022-03-03 15:51 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +    limit = da.meta['gd_prtn_chrg'].to(unit=charge.unit)
Agree. The name is hard coded everywhere. Just like `tof` or `position`. I currently don't see a good way of abstracting away the name, though it will probably have to be adjusted for ESS.

2022-03-03 15:52 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +    return var.to(dtype=bool)
I don't know what those are. The masks loaded by Mantid are stored as floats but all have values of 0 or 1.

2022-03-03 15:54 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +        Name of the instrument.
I hope that we will take a different route. But right now, we need at least one of those options to call the mantid algorithm. We could for now hard code this information in the data array, but until we know how calibrations will be stored at ESS, we have to keep something like the current implementation.

2022-03-03 15:55 UTC, jl-wynen commented on src/ess/diffraction/smoothing.py
> +def fft_smooth(da: sc.DataArray,
Does it have an analogous function? I think it only has frequency filters. But that naming seems confusing here. That being said, I am happy with renaming this function.

2022-03-04 05:09 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    return var.to(dtype=bool)
Mantid has only two types of masks: Pixel masks, and bin-masks. The latter would depend on the TOF dimension. Is that what you have?

2022-03-04 05:11 UTC, SimonHeybrock commented on src/ess/diffraction/smoothing.py
> +def fft_smooth(da: sc.DataArray,
Wel,, you are essentially just calling `butter`?

2022-03-07 09:39 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +        mon = sc.rebin(mon, 'wavelength', wavelength_edges)
I will worry about this when we have a data file with event mode monitors so we can test the code properly.

2022-03-07 09:59 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +                  advanced_geometry=True,
It is not needed. I changed it to `False` now.
But I guess, this functions should be changed to use `load_nexus` for ESS data anyway.

2022-03-07 10:14 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +        return vanadium
We should wait for https://github.com/scipp/scipp/pull/2477 and https://github.com/scipp/scippneutron/issues/236. Otherwise, we would have to implement something more complicated now and refactor in the hopefully near future.

2022-03-07 10:24 UTC, jl-wynen commented on src/ess/diffraction/smoothing.py
> +def fft_smooth(da: sc.DataArray,
But `butter_filtfilt` is not a very descriptive name. Also, I would not but 'butter' into the name because we may want to support different filters (unlikely, but still). We could use `lowpass` or `smooth_using_lowpass`.

2022-03-07 10:41 UTC, SimonHeybrock commented on src/ess/diffraction/smoothing.py
> +def fft_smooth(da: sc.DataArray,
One of the latter two sounds good.

2022-03-08 08:56 UTC, SimonHeybrock commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
> users might want to not even load them if they do everything in terms of calibration parameters 

Aren't they always needed for conversion to wavelength? Positions are not so large, I think it is unlikely that someone may need to skip loading them.

> Do you have any suggestions?

Note sure.

2022-03-08 08:59 UTC, SimonHeybrock commented on src/ess/diffraction/corrections.py
> +    if 'wavelength' not in mon.coords:
iirc you said your answer was based on something that is done below, not my actual question?

2022-03-08 09:00 UTC, SimonHeybrock commented on src/ess/diffraction/grouping.py
> +        data.coords['two_theta'] = scn.two_theta(data)
Somehow I do not see those changes, did you push them?

2022-03-08 09:02 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    limit = da.meta['gd_prtn_chrg'].to(unit=charge.unit)
I think, e.g., `da.meta['gd_prtn_chrg']` should probably be provided as an input to these functions.

2022-03-08 09:05 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +        return vanadium
Did you mean to link scipp/scippneutron#237 instead of 236? The comment here is longer than the code to do the filtering. It is very unclear if and when scipp/scippneutron#237 will provide a "simpler" solution.

2022-03-08 09:11 UTC, SimonHeybrock commented on src/ess/diffraction/powder/conversions.py
> +    return tof_data.rename_dims({'wavelength': 'tof'})
Interesting odd case: Essentially we want to `transform_coords` to `tof`, where `tof` exists (as an attr) but we nevertheless want to remove the things it *could* have been computed from.

Can we avoid this whole mess by rewriting the "conversion with calibration" based on `wavelength`? After all, it is related to `tof` by a simple (pixel-dependent) scaling factor?

2022-03-08 09:12 UTC, SimonHeybrock commented on src/ess/diffraction/powder/corrections.py
> +    out.masks['calibration'] = calibration['mask'].data
So you are loading the masks now?

2022-03-08 10:51 UTC, jl-wynen commented on src/ess/diffraction/grouping.py
> +        data.coords['two_theta'] = scn.two_theta(data)
The diff view can be finicky: https://github.com/scipp/ess/blob/d31c949a5bb696911018345b2e2b1db2c7d742cd/src/ess/diffraction/powder/conversions.py#L34

2022-03-08 10:53 UTC, jl-wynen commented on src/ess/diffraction/powder/corrections.py
> +    out.masks['calibration'] = calibration['mask'].data
They were always loaded. I only added checks to prevent overwriting existing meta data.

2022-03-08 10:54 UTC, jl-wynen commented on src/ess/diffraction/powder/conversions.py
> +    return tof_data.rename_dims({'wavelength': 'tof'})
We could. But I don't want to make it depend on wavelength. It should be able to bypass that. So we would have to detect whether it exists and then use a different function than when it does not exist.

2022-03-08 10:55 UTC, SimonHeybrock commented on src/ess/diffraction/powder/conversions.py
> +    return tof_data.rename_dims({'wavelength': 'tof'})
That would seem cleaner?

2022-03-08 13:03 UTC, jl-wynen commented on src/ess/diffraction/conversions.py
> +        del tof_data.bins.coords['wavelength']
I changed it to use `transform_coords` for handling wavelength and positions. I tried to use descriptive names so that the log message makes sense. Let me know what you think!

2022-03-08 13:05 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +    return data / proton_charge
Note that I removed this function and used division inline instead.

2022-03-08 13:08 UTC, SimonHeybrock commented on src/ess/diffraction/powder/conversions.py
> +        'source_position': _make_dummy
I think I understand the trick you are using here, but anyone less familiar with `transform_coords` probably would not. Maybe add a comment explaining it?

2022-03-08 13:18 UTC, jl-wynen commented on src/ess/diffraction/grouping.py
> +        data.coords['two_theta'] = scn.two_theta(data)
I forgot to make the change. Pushed it now.

2022-03-08 13:29 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +        return vanadium
No, I meant 236. Can we currently get the pulse time reliably from the file? Without that, I don't see how we can filter pulses.

2022-03-08 13:31 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +        return vanadium
We cannot reliably for cases that require high time resolution. The pulse times we get may be off by a couple of pulses. So if the beam is down for 5 minutes the filtering will be fine. If every other pulse is bad then it will be completely wrong.

2022-03-08 13:38 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +    return subtract_empty_instrument(vanadium, empty_instrument)
> Can we find a mechanism that deals with imposing common wavelength (or TOF) binning "upstream" rather than attempting to fix it here?

This would only work if the user never changes the binning or only changes it in a consistent manner.

I agree that simply replacing the binning can go wrong. But that is also the case in tof. We only handle data with a single wavelength bin here, in this case, it is fine to change the bin edges in this way, I think. I can change it to make the change in tof before conversion to wavelength. But that would be entirely equivalent and no less complicated.

2022-03-08 13:40 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    return subtract_empty_instrument(vanadium, empty_instrument)
> We only handle data with a single wavelength bin here, in this case, it is fine to change the bin edges in this way, I think. I can change it to make the change in tof before conversion to wavelength. But that would be entirely equivalent and no less complicated.

That may be the case right now, but sooner or later someone will add masking along TOF, and then this will cause trouble, without necessarily showing up as an error, won't it?

2022-03-08 14:14 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +        return vanadium
I thought the point of your work on frame handling was to figure out the correct pulses?

2022-03-08 14:17 UTC, jl-wynen commented on src/ess/diffraction/load.py
> +    return subtract_empty_instrument(vanadium, empty_instrument)
`data.attrs['tof'] = tof_edges` will fail with a `DimensionError`.

I can change such that `subtract_empty_instrument` requires matching binning and move the edge matching into `load_and_preprocess_vanadium`. There, we are in full control over what happens.

2022-03-08 14:32 UTC, jl-wynen commented on src/ess/diffraction/powder/conversions.py
> +        'source_position': _make_dummy
Can do but that would only help people looking at the code. I think it is more important that the log message makes sense because that is what most people will see. E.g.
```
Transformed coords (difa, difc, position, sample_position, source_position, tof, tzero) -> (dspacing)
  Renamed dimensions:
    dspacing <- tof
  Steps:
    Compute (temp_dspacing_) = dspacing_from_diff_calibration(tof, tzero, difa, difc)
    Compute (dspacing) = _consume_positions(temp_dspacing_, position, sample_position, source_position)
```
or
```
Transformed coords (difa, difc, tof, tzero) -> (dspacing)
  Renamed dimensions:
    dspacing <- tof
  Steps:
    Compute (position) = _make_dummy()
    Compute (sample_position) = _make_dummy()
    Compute (source_position) = _make_dummy()
    Compute (temp_dspacing) = dspacing_from_diff_calibration(tof, tzero, difa, difc)
    Compute (dspacing) = _consume_positions(temp_dspacing, position, sample_position, source_position)
```
I don't think either is particularly easy to understand. I could add a custom log to explain what happens(?)

Also, is the fact that this trick needs a comment a sign that we should manually move / remove coords instead? That would not be pretty but easy to understand?

2022-03-08 14:40 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +        return vanadium
Yes, so shouldn't we assume here that `pulse_time` means `pulse_time`?

2022-03-08 14:41 UTC, SimonHeybrock commented on src/ess/diffraction/load.py
> +    return subtract_empty_instrument(vanadium, empty_instrument)
Yes, let us do that. Is the function even required?

2022-03-08 14:42 UTC, SimonHeybrock commented on src/ess/diffraction/powder/conversions.py
> +        'source_position': _make_dummy
Until we actually encounter data without the coords, can we just pretend they are always there? It feels like you are trying to fix hypothetical problems?

2022-03-08 14:53 UTC, jl-wynen commented on src/ess/diffraction/powder/conversions.py
> +        'source_position': _make_dummy
Ok. But I would still not like to add them as arguments to `dspacing_from_diff_calibration` because that makes it look as though they are used to compute d-spacing.

2022-03-21 12:21 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "First, we import all required modules.\n",
Delete?

2022-03-21 12:21 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "**Note** that we load functions from `external` modules.\n",
Just add this as an inline comment of the import?

2022-03-21 12:21 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "scn.instrument_view(\n",
Make this into a `powgen.instrument_view()` that would define the camera parameters?
Even if it's only a single parameter, more params could be added later (such as other beamline components etc...)

2022-03-21 12:21 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "vana = diffraction.load_and_preprocess_vanadium(\n",
Not sure I understand why there needs to be a function which is specific to vanadium. Is it doing something different that for the sample file above? Could it just be a `load_and_preprocess` function?

2022-03-21 12:21 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "Have a look at the log widget at the top of the notebook.\n",
This is reading more like a tutorial than an actual workflow.
I think it's fine to add more details about what the function is doing internally, but I think I would rephrase this.
Something like

`load_and_preprocess_vanadium` applies a crude, preliminary event filtering mechanism whereby events are discarded when the proton charge is too low (a message is visible in the log...)

?

2022-03-21 12:21 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "We could plot is as is, but we histogram manually in order to have control over the bins."
I would just remove this, as the automatic binning mechanism is going to go away in the future anyway.
I think it's fine to just have the histogramming without justification.

2022-03-21 12:21 UTC, nvaytet commented on src/ess/diffraction/corrections.py
> +                         smooth_args: Optional[Dict[str, Any]] = None) -> sc.DataArray:
I think this function should do what the name says, i.e. normalize, instead of normalizing and smoothing.
There should be a separate function that does the smoothing that the user can call before calling this one.

2022-03-21 12:21 UTC, nvaytet commented on src/ess/diffraction/grouping.py
> +def focus_by_two_theta(data: sc.DataArray,
Is 'focus' a Mantid specific term? Should we avoid and use e.g. `group_by_two_theta` which is more explicit as to what is going on inside the function?

2022-03-21 12:28 UTC, SimonHeybrock commented on src/ess/diffraction/grouping.py
> +def focus_by_two_theta(data: sc.DataArray,
It might be powder-diffraction-specific, ask Celine.

2022-03-21 14:26 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "First, we import all required modules.\n",
Only the last line or everything?

2022-03-21 14:27 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "**Note** that we load functions from `external` modules.\n",
Why? Do we have guidelines for what goes into the code and what into markdown? I typically lean towards putting as much as possible into markdown because it is easier to format.

2022-03-21 14:29 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "vana = diffraction.load_and_preprocess_vanadium(\n",
It subtracts the empty instrument measurement which is not done for the sample.
I am definitely not a fan of this function because it is so specific and high-level. But the only alternative I see is inlining the code in the notebook which would not help readability. Do you have a better idea?

2022-03-21 14:31 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "Have a look at the log widget at the top of the notebook.\n",
Are these notebooks really meant as production grade workflows? I thought those would be in `ess-notebooks` and here we explain how reduction works in principle.

2022-03-21 14:36 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +                         smooth_args: Optional[Dict[str, Any]] = None) -> sc.DataArray:
Then, the normalisation would be trivial, just `x.bins /= lookup(y)`. We would require the user to first convert to wavelength, then smooth, and then divide.

This is basically showing the problem of where to draw the line between tools provided by ess and what users need to write in notebooks. In this particular case, my objection to putting this into the notebook is that it is easy to make a mistake in the individual steps or forget to smooth. And ~10 lines of code in a notebook are harder to read than a single function, IMHO.

2022-03-21 14:47 UTC, jl-wynen commented on src/ess/diffraction/grouping.py
> +def focus_by_two_theta(data: sc.DataArray,
Celine says, it might even be SNS-specific. I'll rename.

2022-03-21 22:02 UTC, nvaytet commented on src/ess/diffraction/corrections.py
> +                         smooth_args: Optional[Dict[str, Any]] = None) -> sc.DataArray:
My problem is more that the function name could mislead the user to think it's just normalizing.

An alternative would be to just change the function name to reflect that it is doing more than just normalizing.

2022-03-21 22:03 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "Have a look at the log widget at the top of the notebook.\n",
In my mind it was the other way round. Official reduction under ci control in ess, and ess-notebooks is a place for users to store and share notebooks?

2022-03-21 22:05 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "First, we import all required modules.\n",
The last line. I think it's obvious that we are importing modules from the code cell?

2022-03-21 22:08 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "**Note** that we load functions from `external` modules.\n",
My idea was that this would go away in the future when we have a workflow for dream, and it would then be easier to update the notebook.

We don't have guidelines on this. It was just a suggestion, I don't have strong feelings either way.

2022-03-23 10:32 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "**Note** that we load functions from `external` modules.\n",
The entire markdown cell has to be replaced. So I'd rather leave it as it is.

2022-03-23 10:55 UTC, jl-wynen commented on src/ess/diffraction/corrections.py
> +                         smooth_args: Optional[Dict[str, Any]] = None) -> sc.DataArray:
Not sure what would be a good name. Something like `normalize_by_smooth_monitor` does not really work because smoothing is optional.

2022-03-30 08:23 UTC, nvaytet commented on src/ess/external/powgen/instrument_view.py
> +                               pixel_size=pixel_size,
Why did you list these 3 arguments explicitly? They seem to just be forwarded to the scippneutron `instrument_view`.
Can't they just be part of the `kwargs`?
Is it because you wanted to have the type-hints? I see they are missing from the scippneutron `instrument_view`. Maybe we should add them there instead?

2022-03-30 08:32 UTC, jl-wynen commented on src/ess/external/powgen/instrument_view.py
> +                               pixel_size=pixel_size,
These are the explicit arguments of `instrument_view`. Listing them explicitly means that they can be found by `help(powgen.instrument_view)`, autocompletion, etc.

2022-03-30 08:35 UTC, nvaytet commented on src/ess/diffraction/grouping.py
> +def focus_by_two_theta(data: sc.DataArray,
Don't forget to rename `focus` to something else ;-)

2022-03-30 08:52 UTC, jl-wynen commented
I disabled the failing tests because this is a bug in Mantid. See https://github.com/mantidproject/mantid/issues/33690

2022-03-30 08:53 UTC, nvaytet commented on src/ess/diffraction/corrections.py
> +                         smooth_args: Optional[Dict[str, Any]] = None) -> sc.DataArray:
ok let's keep it as is.

2022-03-30 14:39 UTC, nvaytet approved these changes

2022-03-30 14:46 UTC, nvaytet requested changes
There seems to be an issue with the filtering by proton charge.
![Screenshot at 2022-03-30 16-46-15](https://user-images.githubusercontent.com/39047984/160863075-83ccd98b-3089-45ac-a016-b9b805464c3b.png)

2022-04-12 12:45 UTC, jl-wynen commented
I disabled handling of the empty instrument data because I can't seem to get it to work with normalisation by proton charge. See the long comment in `load.py`. Please let me know if you have a better idea! (@celinedurniak)

2022-04-25 11:18 UTC, celinedurniak commented
@jl-wynen With the set of POWGEN data files we are using, I think the option you chose after normalisation by proton charge is fine.

2022-04-25 11:58 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "### Focus into $2\\theta$ bins"
We renamed 'focus' to 'group' in the python function. Should we also remove the term Focus here?

2022-04-25 11:58 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "sample_focussed = diffraction.group_by_two_theta(sample_dspacing,\n",
```suggestion
    "sample_grouped = diffraction.group_by_two_theta(sample_dspacing,\n",
```

2022-04-25 11:58 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "vana_focussed = diffraction.group_by_two_theta(vana_dspacing, edges=two_theta)"
```suggestion
    "vana_grouped = diffraction.group_by_two_theta(vana_dspacing, edges=two_theta)"
```

2022-04-25 11:58 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "sc.histogram(all_spectra, bins=dspacing_edges).plot()"
Why the strange unit on the y axis?
![Screenshot at 2022-04-25 13-51-38](https://user-images.githubusercontent.com/39047984/165084378-6a81c7bb-2368-49f2-a584-40c7d7ea95f0.png)

2022-04-25 11:58 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "For a better resolution, we now group ('focus') the sample and vanadium data into a number of bins in the scattering angle [$2\\theta$](https://scipp.github.io/scippneutron/user-guide/coordinate
Something seems to go wrong in sphinx with the rendering of math in a link?
![Screenshot at 2022-04-25 13-51-44](https://user-images.githubusercontent.com/39047984/165084477-fc411289-e88e-4962-a9c2-c3fdd3c87b5b.png)

2022-04-25 12:53 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "sc.histogram(all_spectra, bins=dspacing_edges).plot()"
Don't know. Must be some strange scaling in the unit from dividing them for normalisation.

2022-04-25 13:02 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "sc.histogram(all_spectra, bins=dspacing_edges).plot()"
The sample and vanadium have different units for the proton charge. When dividing them, we get the 2.7e-10 scale in the plot. I changed `normalize_by_vanadium` to convert to `unit='one'` to eliminate the scale.

2022-04-25 13:07 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "For a better resolution, we now group ('focus') the sample and vanadium data into a number of bins in the scattering angle [$2\\theta$](https://scipp.github.io/scippneutron/user-guide/coordinate
Good catch!

2022-04-25 13:10 UTC, jl-wynen commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "### Focus into $2\\theta$ bins"
Removed all mentions of 'focus'

2022-04-25 13:57 UTC, nvaytet reviewed
Looking good. Just one more suggestion for hiding the long url.

In addition, I don't see anything in the release notes.
Can you add something?

Thanks

2022-04-25 13:57 UTC, nvaytet commented on docs/instruments/external/powgen/powgen_reduction.ipynb
> +    "For a better resolution, we now group the sample and vanadium data into a number of bins in the scattering angle $2\\theta$ (https://scipp.github.io/scippneutron/user-guide/coordinate-transforma
```suggestion
    "For a better resolution, we now group the sample and vanadium data into a number of bins in the scattering angle $2\\theta$ (see [here](https://scipp.github.io/scippneutron/user-guide/coordinate-transformations.html))\n",
```

2022-04-25 14:34 UTC, nvaytet approved these changes

2022-04-25 14:42 UTC, merged