File writing and the Orso object
scipp/ess-legacy-v2 pull request #115
Opened 2022-04-04 16:00 UTC by arm61

Add necessary functionality and an example of file writing, calculation of resolution function and the including of the orso object that is populated throughout

2022-04-04 16:17 UTC, arm61 commented
How do I add a `pip` package? `orsopy` is only on `pip` currently.

2022-04-05 06:49 UTC, arm61 commented
For now (to get things to build) I have added a `wget` and install for `orsopy` but that is obviously not ideal. I couldn't work out how to include `pip` dependencies.

2022-04-05 12:28 UTC, nvaytet reviewed
Some more comments, unrelated to our discussion on wrapping code in cells into functions in the `reflectometry` or `amor` modules.

2022-04-05 12:28 UTC, nvaytet commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
This is fine :+1:

2022-04-05 12:28 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "The resolution function for these measurements involves combining a few contributing elements. \n",
I feel we start talking about resolution function a bit out of the blue. Maybe making a new notebook subsection would help?

2022-04-05 12:28 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "sample.coords['sample_size_resolution'] = sc.scalar(0.18) * sc.to_unit(sample.coords['sample_size'], 'm') / sample.coords['position'].fields.z"
Where does the `0.18` come from?

2022-04-05 12:28 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "sample = amor.load(amor.data.get_path(\"sample.nxs\"), owner, sample, creator, 'amor_reduction.ipynb', \n",
Use keyword arguments?

2022-04-05 12:28 UTC, nvaytet commented on src/ess/reflectometry/save.py
> +from orsopy import fileio
You are making `orso` a hard dependency of `ess.reflectometry`. Is that what we want to do, or do we want to have it optional?

2022-04-05 12:28 UTC, nvaytet commented on src/ess/reflectometry/save.py
> +    sq = data_array.coords['sigma_Q_by_Q'].max('detector_id').values * q
I would perform the operation on the scipp variables, and extract the `.values` afterwards, as you are dropping variances and also ignoring potentially mismatching units.

2022-04-05 12:28 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "normalized.coords['sigma_Q_by_Q'] = sc.sqrt(\n",
How is the `sigma_Q` used in the analysis? Is it related to the variances of the `sample_q` quantity, or is it a separate quantity?
Should the variances of `sample_q` contribute to `sigma_Q`?

2022-04-05 12:28 UTC, nvaytet commented on src/ess/amor/beamline.py
> +        chopper_chopper_distance = sc.scalar(0.49, unit='m')
Remove parameter and compute distance from chopper positions.

2022-04-05 12:28 UTC, nvaytet commented on src/ess/amor/load.py
> +
Move into `populate_orso()`

2022-04-05 13:26 UTC, arm61 commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
This means if someone wants to use `ess.reflectometry` they need to `conda install ess` then `pip install orsopy` yeah?

2022-04-05 13:32 UTC, arm61 commented on src/ess/reflectometry/save.py
> +from orsopy import fileio
I think it should be a hard dependency. If you wanna write files, you need `orsopy`.

2022-04-05 14:37 UTC, nvaytet commented on src/ess/reflectometry/save.py
> +from orsopy import fileio
Sure, but maybe you want to simply load an amor file and make a plot?
I am worried that we will have 200 different dependencies for all the different techniques. I think we should make it optional? I will ask Simon what he thinks.

2022-04-05 14:38 UTC, nvaytet commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
Well we would add `orsopy` in the list of dependencies in the recommended env file for using `ess`

2022-04-06 09:04 UTC, jl-wynen commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
You should be able to install directly from the remote URL with pip:
```
pip install https://files.pythonhosted.org/packages/9d/b4/761a6da7e1dedf793a6c3410cf362e2b61092a8fd8267d5ebc88e71f1fc5/orsopy-0.0.5-py2.py3-none-any.whl
```

See, e.g., point 8 in https://pip.pypa.io/en/stable/cli/pip_install/

2022-04-06 09:04 UTC, jl-wynen commented on src/ess/amor/load.py
> +         reduction_script: str,
Can the ORSO related arguments be combined into a single structure? This might simplify things moving forward in case you need to add more arguments or if they are loaded from a common place (e.g. SciCat)

2022-04-06 09:04 UTC, jl-wynen commented on src/ess/reflectometry/save.py
> +from orsopy import fileio
Does `save.py` have to be imported by `__init__.py`?

2022-04-06 09:04 UTC, jl-wynen commented on src/ess/reflectometry/save.py
> +def save(data_array: sc.DataArray, filename: str):
```suggestion
def save_orso(data_array: sc.DataArray, filename: str):
```
?

2022-04-06 09:04 UTC, jl-wynen commented on src/ess/reflectometry/save.py
> +    q = sc.midpoints(data_array.mean('detector_id').coords['Q'])
You should check if Q is actually bin-edges.

2022-04-06 10:57 UTC, arm61 commented on src/ess/reflectometry/save.py
> +from orsopy import fileio
Fair point, does this maybe suggest at the `ess` level there should be different dependency levels/categories?

2022-04-06 10:58 UTC, arm61 commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
I tried this (and maybe did it wrong) but then found something saying that this didn't work for conda envs

2022-04-06 11:04 UTC, jl-wynen commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
ok

2022-04-06 11:12 UTC, arm61 commented on docs/instruments/amor/amor_reduction.ipynb
> +    "normalized.coords['sigma_Q_by_Q'] = sc.sqrt(\n",
The `sigma_Q` is the resolution of each `Q` points so not linked to the variances in the `sample_q`.

2022-04-06 13:07 UTC, arm61 commented on src/ess/reflectometry/save.py
> +    q = sc.midpoints(data_array.mean('detector_id').coords['Q'])
What as the conclusion on how to achieve this?

2022-04-06 13:08 UTC, arm61 commented on src/ess/reflectometry/save.py
> +def save(data_array: sc.DataArray, filename: str):
I am going for `save_ort` cause in future there might be a NeXus version of the ORSO format.

2022-04-06 13:09 UTC, arm61 commented on src/ess/amor/load.py
> +         reduction_script: str,
In future, `owner` and `sample` will be in the raw NeXus, so these will be removed when this is the case.

2022-04-06 13:49 UTC, jl-wynen commented on src/ess/reflectometry/save.py
> +    q = sc.midpoints(data_array.mean('detector_id').coords['Q'])
Use this? https://scipp.github.io/generated/classes/scipp.Coords.html#scipp.Coords.is_edges

2022-04-06 13:52 UTC, jl-wynen commented on src/ess/reflectometry/conversions.py
> +                      graph: dict = specular_reflection()) -> sc.DataArray:
```suggestion
                      graph: dict = None) -> sc.DataArray:
```
And later
```.py
graph = graph if graph is not None else specular_reflection()
```
in order to avoid a mutable default argument.

2022-04-06 14:26 UTC, arm61 commented on src/ess/reflectometry/save.py
> +    q = sc.midpoints(data_array.mean('detector_id').coords['Q'])
This is new?

2022-04-06 14:27 UTC, arm61 commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
Sorry @jl-wynen that comment was to @nvaytet not yourself

2022-04-07 06:49 UTC, arm61 commented
![Screenshot 2022-04-06 at 15 22 56](https://user-images.githubusercontent.com/15774281/162137353-a7c6e14b-de86-402f-8945-77ea350e0f91.png)

`yap` is rewriting my file and making it fail `flake8` 😢

2022-04-07 07:05 UTC, arm61 commented
Looks like `yapf` and `flake8` are playing nicely again.

2022-04-07 07:17 UTC, jl-wynen commented on src/ess/reflectometry/save.py
> +    q = sc.midpoints(data_array.mean('detector_id').coords['Q'])
Added in 0.13

2022-04-07 08:43 UTC, arm61 commented
Requesting a re-view from you both writing tests in the meantime (though those can be put in a future PR).

2022-04-07 11:42 UTC, jl-wynen reviewed
We switched to using numpy-style docstrings because they are more readable (https://github.com/scipp/scipp/pull/2432). sphinx in `ess` uses the napoleon extension to make this work.
I'm not asking you to change the docstrings now, but when you add more functions in the future, you can use numpy-style and step by step change the existing ones.

2022-04-07 11:42 UTC, jl-wynen commented on docs/techniques/reflectometry/reference.rst
> +   save.save
```suggestion
   save.save_ort
```
Please build the docs and check for warnings / errors.

2022-04-07 11:42 UTC, jl-wynen commented on src/ess/amor/normalise.py
> +def normalise_by_supermirror(sample: sc.DataArray,
I believe this should be 'normalize' (also rename file) because we decided to use American spelling.

2022-04-07 12:13 UTC, arm61 commented on src/ess/amor/normalise.py
> +def normalise_by_supermirror(sample: sc.DataArray,
American spelling makes me sad 🤣

2022-04-07 14:56 UTC, arm61 commented
> We switched to using numpy-style docstrings because they are more readable ([scipp/scipp#2432](https://github.com/scipp/scipp/pull/2432)). sphinx in `ess` uses the napoleon extension to make this work.
> I'm not asking you to change the docstrings now, but when you add more functions in the future, you can use numpy-style and step by step change the existing ones.

I used to use `numpy` style and now my brain is trained on `sphinx` style 🤣 . Will adapt gradually!

2022-04-08 07:53 UTC, jl-wynen approved these changes

2022-04-08 09:12 UTC, nvaytet requested changes
I think the notebook looks much cleaner now. Nice job! :+1: 
Some more comments, should be the final round of changes.

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/beamline.py
> +                     phase=chopper_phase,
Are the phases the same for the two choppers?
I don't think it affects the workflow here but i'm slightly surprised.
Or maybe it's the cut-out angles that are different, thus making the choppers optically blind?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/calibrations.py
> +    m_value: sc.Variable = sc.scalar(5, unit=sc.units.dimensionless),
Should we also use `None` and set the default values in the function body?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/load.py
> +        populate_orso(data, filename, owner, sample, creator, reduction_script))
Use keyword args?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/load.py
> +def populate_orso(data: sc.DataArray, filename: str, owner: fileio.base.Person,
Does the Orso standard say that all these entries are mandatory, or are some of them optional?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/normalize.py
> +        raise UserWarning("For metadata to be logged in the data array, "
By using `raise` you are generating an actual error, instead of a warning. You should use `warnings.warn()` if you don't want the workflow to be interrupted if orsopy is not installed.

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/beamline.py
> +                  chopper_1_position: sc.Variable = None,
The names `chopper_1` and `chopper_2` end up in many places of the code. In the WFM, I tried to use names that were a little more descriptive, such as `chopper_near` and `chopper_far`.
However, I realised that it could also be unclear, because you could ask "does `chopper_near` mean near the source or near the sample?"
So just a suggestion. I guess `chopper_1` could be interpreted as being the first chopper the neutrons meet along their flight path, so maybe it's just as good?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/resolution.py
> +    Find the wavelength resolution contribution as described in Secion 4.3.3 of the Amor
```suggestion
    Find the wavelength resolution contribution as described in Section 4.3.3 of the Amor
```

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/resolution.py
> +    The resolution from the projected sample size, where is may be bigger
"where is may be bigger" ?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/resolution.py
> +    than the detector pixel resolution as described in Secion 4.3.3 of the Amor
```suggestion
    than the detector pixel resolution as described in Section 4.3.3 of the Amor
```

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/resolution.py
> +    Determine the angular resolution as described in Secion 4.3.3 of the Amor
```suggestion
    Determine the angular resolution as described in Section 4.3.3 of the Amor
```
(the wonders of copy/paste...)

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/resolution.py
> +    return fwhm_to_std(sc.to_unit(sample_size, 'm') / pixel_position.fields.z)
Should we also convert the `pixel_position.fields.z` to `m` ? to make sure they have the same unit?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/amor/resolution.py
> +        detector_spatial_resolution / pixel_position.fields.z)) / theta
This will throw an error if ` detector_spatial_resolution` and `pixel_position.fields.z` don't have the same unit. e.g. `cm` and `m`. Should we convert both to e.g. `m` as you've done for `sample_size` above?
Should we also convert the result of the `atan` to the unit of `theta`? Since we recently discovered that dividing `deg` by `rad` does weird things with the unit...

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/__init__.py
> +from . import save
Should we make an `io` module that would also contain loaders? Would you ever need to read from an orso file to get info into a notebook? (not suggesting to implement an orso reader now, but might be good to think about where it would go if we need one in the future?)

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/conversions.py
> +        raise UserWarning("For metadata to be logged in the data array, "
replace `raise` with `warnings.warn`

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/conversions.py
> +        data_array_q = sc.bin(data_array_q, edges=[q_edges])
You are not logging to orso here. Is it because the Q values are the final data form you are saving to the orso file anyway, so you don't need to log the range of values?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/corrections.py
> +        warnings.warn(
This comes up a lot, can you make it a single function somewhere and call that?
Something like 
```Py
def check_orso():
    try:
        from orsopy import fileio
    except ImportError:
        warnings.warn("To store information about corrections it is "
            "necessary to install the orsopy package.", UserWarning)
        return False
    return True

...
if check_orso():
     data_array_fp_correction.attrs['orso'].value.reduction.corrections += [
            'footprint correction'
        ]
```
I think `check_orso()` should then probably also be used when you are first creating the orso attr while loading the files?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/corrections.py
> +    Parmaeters
```suggestion
    Parameters
```

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/save.py
> +        raise UserWarning("The expected output file ending is .ort.")
```suggestion
        raise ValueError("The expected output file ending is .ort.")
```
?

2022-04-08 09:12 UTC, nvaytet commented on src/ess/reflectometry/save.py
> +    q = data_array.mean('detector_id').coords['Q']
Will the dimension always be `detector_id`? Or should we make it a function arg that defaults to `detector_id`?
`detector_id` could be Amor-specific, while this lives in the `reflectometry` module.

2022-04-08 09:12 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "    sample.coords['source_chopper_1'].value['position'], sample.coords['source_chopper_2'].value['position'], sample.coords['position'])"
Use keyword args?

2022-04-08 09:12 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "    sample.coords['position'], sample_theta.bins.coords['theta'], sample_theta.coords['detector_spatial_resolution'])"
kwargs?

2022-04-08 09:12 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "sample_theta.coords['sample_size_resolution'] = amor.resolution.sample_size_resolution(sample.coords['position'], sample.coords['sample_size'])"
kwargs and split the long line?

2022-04-08 09:12 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "sample_theta.coords['sample_size_resolution'] = amor.resolution.sample_size_resolution(sample.coords['position'], sample.coords['sample_size'])"
So are the resolution computations Amor specific or could they live in the `reflectometry` module?

2022-04-08 09:16 UTC, nvaytet commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
In this file https://github.com/scipp/ess/blob/main/docs/environments/ess.yml, add a section with
```
  - pip
  - pip:
    - orsopy
```

2022-04-08 09:29 UTC, nvaytet commented on src/ess/reflectometry/corrections.py
> +        warnings.warn(
Now that I read the code again, this wouldn't be so nice in the cases where you are doing
```Py
    try:
        from orsopy import fileio
        data_array_theta.attrs[
            'orso'].value.data_source.measurement.instrument_settings.incident_angle = (
                fileio.base.ValueRange(......
```
because changing it to
```
    if check_orso():
        from orsopy import fileio
        data_array_theta.attrs[
            'orso'].value.data_source.measurement.instrument_settings.incident_angle = (
                fileio.base.ValueRange(
```
would mean importing `orsopy` twice...

You could:
1. Simply make a function that makes the common error message, and keep the rest as is
2. Something like this, but I find it kind of dodgy/hacky
```Py
def check_orso():
    try:
        from orsopy import fileio
        return fileio
    except ImportError:
        warnings.warn("To store information about corrections it is "
            "necessary to install the orsopy package.", UserWarning)
        return False

...
if (orso_fileio := check_orso()):
     data_array_theta.attrs[
            'orso'].value.data_source.measurement.instrument_settings.incident_angle = (
                orso_fileio.base.ValueRange(
```

2022-04-08 12:11 UTC, arm61 commented on src/ess/amor/beamline.py
> +                     phase=chopper_phase,
This chopper is an optically blind system achieved with two phase matched choppers that are 1 m apart.

2022-04-08 12:12 UTC, arm61 commented on src/ess/amor/normalize.py
> +        raise UserWarning("For metadata to be logged in the data array, "
Yes. I started correcting this but is it still in progress cause I got distracted by shiny things probably.

2022-04-08 12:13 UTC, arm61 commented on docs/instruments/amor/amor_reduction.ipynb
> +    "sample_theta.coords['sample_size_resolution'] = amor.resolution.sample_size_resolution(sample.coords['position'], sample.coords['sample_size'])"
I expect them to be Amor specific.

2022-04-08 12:14 UTC, arm61 commented on src/ess/amor/beamline.py
> +                  chopper_1_position: sc.Variable = None,
I didn't really like `_1` and `_2` but I agree it is difficult to have something perfect. I am happy to go with a standard that we invent?

2022-04-11 06:30 UTC, arm61 commented on src/ess/reflectometry/conversions.py
> +        data_array_q = sc.bin(data_array_q, edges=[q_edges])
Essentially yes, there it nothing in this conversion that is an essential or optional input in the ORSO object.

2022-04-11 06:44 UTC, arm61 commented on src/ess/reflectometry/__init__.py
> +from . import save
This is a good idea cause in future there might be a function to read in ort as you say.

2022-04-11 06:49 UTC, arm61 commented on src/ess/amor/load.py
> +def populate_orso(data: sc.DataArray, filename: str, owner: fileio.base.Person,
There are all mandatory in the ORSO format.

2022-04-11 06:55 UTC, arm61 commented on src/ess/amor/load.py
> +        populate_orso(data, filename, owner, sample, creator, reduction_script))
Do you mean like passing a dict to `load`, cause the seems weird if all the inputs are requirements.

2022-04-11 07:31 UTC, nvaytet commented on src/ess/amor/load.py
> +        populate_orso(data, filename, owner, sample, creator, reduction_script))
No i meant 
```Py
populate_orso(data=data, filename=filename, owner=owner, sample=sample, creator=creator, reduction_script=reduction_script))
```

This prevents someone in the future just swapping round to arguments by mistake and the error going unnoticed until you inspect the metadata in the file and you find out the owner has not become the sample...

2022-04-11 07:32 UTC, arm61 commented on src/ess/amor/load.py
> +        populate_orso(data, filename, owner, sample, creator, reduction_script))
Ah gotcha

2022-04-11 07:41 UTC, arm61 commented on conda/meta.yaml
> +    - pip install orsopy-0.0.5-py2.py3-none-any.whl
Yeah I tried that in b5088c9e95aac765e45011fb4b9912484adf2ab6 and the build failed because `ValueError: Dictionaries are not supported as values in requirements sections.  Note that pip requirements as used in conda-env environment.yml files are not supported by conda-build.
[31](https://github.com/scipp/ess/runs/5828761443?check_suite_focus=true#step:5:31)`

2022-04-11 07:51 UTC, nvaytet commented on src/ess/amor/resolution.py
> +                sc.to_unit(pixel_position.fields.z, 'm')), theta.bins.unit)) / theta
With `theta.bins.unit`, this function can only be used for event data. Maybe someone would want to use it on histogrammed data?
We could do something like
```Py
angle_unit = theta.bins.unit if theta.bins is not None else theta.unit
```
?

In addition, we should probably add a `copy=False` to all our `to_unit` calls, because calling this on event data will make many copies of potentially very large data.

2022-04-11 07:51 UTC, nvaytet commented on src/ess/amor/calibrations.py
> +        m_value = sc.scalar(5, unit=sc.units.dimensionless)
Now that we don't have the default values in the function call, maybe it would be worth mentioning the default values in the docstring?

2022-04-11 07:57 UTC, arm61 commented on src/ess/amor/resolution.py
> +                sc.to_unit(pixel_position.fields.z, 'm')), theta.bins.unit)) / theta
Also added `copy=False` to the `to_unit` that is on the pixels but not for the sample size or detector resolution cause these will be single values.

2022-04-11 10:49 UTC, nvaytet approved these changes

2022-04-11 10:50 UTC, merged