Amor reflectometry
scipp/ess-legacy-v2 pull request #15
Opened 2021-04-15 12:10 UTC by arm61

This is the _first draft_ of the Amor/reflectometry reduction code. Somethings to note:
- it is not feature complete
- test coverage for the reflectometry modules is 100 % (not including the plotting stuff)
- there is currently no testing for the amor package (this is a todo once the code is feature complete)

2021-04-15 12:17 UTC, arm61 commented
The CI is failing cause of line length (in comments and docstrings not in code) and one convenience import in a `__init__.py`. Any flexibility of `flake8`?

2021-04-15 12:39 UTC, arm61 commented
I am not familiar enough with yapf to know what it doesn't like now...seems to be all of the code 🤣

2021-04-15 14:12 UTC, arm61 commented
🎉

2021-04-16 05:31 UTC, SimonHeybrock reviewed
Part 1 (have not looked at all files yet):

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/resolution.py
> +        z_sample_position (`sc.Variable`): The position of the sample in the z-dimension.
This assumes that the sample-normal vector is in `z` direction? Is there a reasonable way to make this independent, e.g., by requiring to either specify it, or storing it as a coord in the data?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/plot.py
> +    return sc.plot(data.wavelength_theta_bin().bins.sum())
By calling `bins.sum()` we limit how useful these functions can be. Is the reason for this https://github.com/scipp/scipp/issues/1564?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/__init__.py
> +G_ACC = -g * (sc.units.m / (sc.units.s * sc.units.s))
Maybe we should make this a vector?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Masking individual event will become very costly very quickly as we get more data. My intention for masking binned data was to use it as follows (assuming you don't have other wavelength binning yet):

```python
wavelength = sc.array(dims=['wavelength'],
                      unit=sc.units.angstrom,
                      values=[wavelength_global_min, wavelength_min, wavelength_max, wavelength_global_max])
binned = sc.bin(binned, edges=[wavelength])
binned.masks['mymask'] = sc.array(dims=['wavelength'], values=[False, True, False])
```

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +        tof_offset = self.tau * self.chopper_phase / 180.0
Assumes phase in in `deg`? Consider using units to avoid bugs?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +        tof_e = self.data.bins.constituents["data"].coords["tof"]
Same as `tof` above?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +        buf.coords["tof"] = tof
Not clear to me what is done here. What is the remaining being used for?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +        chopper_phase=-8.0 * sc.units.dimensionless,
Should this have a `rad` or `deg` unit?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +            sample_size (`sc.Variable`, optional): Size of the sample in direction of the beam. Optional, default `0.01 m`.
Is this a variant of Sphinx/rst I am not aware of? If not, can use use Sphinx syntax for the docstrings?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
Have you considered using the same mechanism as used by `scippneutron.convert`? See https://scipp.github.io/scippneutron/user-guide/unit-conversions.html#Beamline-geometry-parameters-used-in-unit-conversions and https://scipp.github.io/scippneutron/user-guide/overview.html#beamline-geometry? I would generally suggest:

- Store beamline parameters as coords or attrs with data.
- Use [beamline geometry function](https://scipp.github.io/scippneutron/user-guide/overview.html#beamline-geometry) to obtain what is actually needed.

In this case you seem to ignore X (is the beam in Y direction?), but can we just use, e.g., `scn.scattered_beam()` and a `g` vector for the computation?

Even if we store the parameters as coords or attrs, it can still make sense to have this as a function that directly uses the parameters instead of extracting them from a data array. In that case, I would still recommend to work with the "derived" parameters (scattered_beam) instead of underlying positions, since the latter do not actually matter?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +    return angle
- Working in `deg` seems odd. What is wrong with `rad`? Is this user-facing?
- Is `to_unit` not working for `deg`/`rad` conversion?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
Since this includes `velocity` I assume this contains the `event` dimension (or is a binned variable)? In that case, performance matters, so we should avoid repeated work and memory allocations. Most important is probably to ensure that we do the minimum number of operations with it. As written above, I count 5 operations involving `v**2`.

If I parsed the parenthesis correctly, we can rewrite as `(-0.5 g dz) / (v**2) + dy/dz` which is just 2?

Furthermore, once we did the first operation, we should do the second one in-place, to avoid further memory allocations:

```python
out = (-0.5 * g * dz) / (v**2)
out += dy / dz
return out
```
or something like that.

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +    scale_factor = erf((sample_size / beam_on_sample * 2.35482).values)
- What is the magic number?
- Return a scipp variable instead of a numpy array?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +    if ((sc.mean(beam_on_sample)) > sample_size).values:
```suggestion
    if ((sc.mean(beam_on_sample)) > sample_size).value:
```
if this is expected to have only a single value?

2021-04-16 05:31 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +                                 dims=theta.dims) * sample_size
Is this doing a broadcast? Can you use https://scipp.github.io/generated/scipp.broadcast.html#scipp.broadcast?

2021-04-16 07:00 UTC, arm61 commented
> Part 1 (have not looked at all files yet):

Why I opened it now and not when feature complete!

2021-04-16 07:03 UTC, arm61 commented on src/ess/reflectometry/resolution.py
> +        z_sample_position (`sc.Variable`): The position of the sample in the z-dimension.
de7b8de

2021-04-16 07:04 UTC, arm61 commented on src/ess/reflectometry/plot.py
> +    return sc.plot(data.wavelength_theta_bin().bins.sum())
What should be used instead?

2021-04-16 07:05 UTC, arm61 commented on src/ess/reflectometry/__init__.py
> +G_ACC = -g * (sc.units.m / (sc.units.s * sc.units.s))
What benefit would a vector bring?

2021-04-16 07:06 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
I don't really understand the above code... what is `binned`, it is created from itself?

2021-04-16 07:06 UTC, SimonHeybrock commented on src/ess/reflectometry/plot.py
> +    return sc.plot(data.wavelength_theta_bin().bins.sum())
If this is 2D data, you can just `sc.plot(data.wavelength_theta_bin())`, it will then dynamically resample the events (and will also work if data is histogrammed). If it is 1D you have to wait for the issue to be fixed.

2021-04-16 07:08 UTC, SimonHeybrock commented on src/ess/reflectometry/__init__.py
> +G_ACC = -g * (sc.units.m / (sc.units.s * sc.units.s))
Making us independent of different definitions of where "up" is in the lab, potentially avoiding bad bugs if at any point you make an assumption about this (and someone changes the coord system definition).

2021-04-16 07:10 UTC, arm61 commented on src/ess/amor/amor.py
> +        tof_e = self.data.bins.constituents["data"].coords["tof"]
6508389

2021-04-16 07:10 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
It is you binned data, `self.data` in this case, I think.

2021-04-16 07:12 UTC, arm61 commented on src/ess/amor/amor.py
> +        buf.coords["tof"] = tof
This is also not exactly clear to me. The source of neutrons at AMOR is defined by the chopper (they have a continuous source), to the `event_time_offset` in the `.nxs` file is not correct. This is taken from the original code that AMOR provided, but I am speaking to the scientists today to check what is means.

2021-04-16 07:14 UTC, arm61 commented on src/ess/amor/amor.py
> +        chopper_phase=-8.0 * sc.units.dimensionless,
23ccd0c

2021-04-16 07:14 UTC, arm61 commented on src/ess/amor/amor.py
> +        tof_offset = self.tau * self.chopper_phase / 180.0
23ccd0c

2021-04-16 07:15 UTC, arm61 commented on src/ess/amor/amor.py
> +            sample_size (`sc.Variable`, optional): Size of the sample in direction of the beam. Optional, default `0.01 m`.
This is google style sphinx syntax (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

2021-04-16 07:19 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +            sample_size (`sc.Variable`, optional): Size of the sample in direction of the beam. Optional, default `0.01 m`.
Does this require plugins to Sphinx?

2021-04-16 07:23 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +    return angle
- plotting of theta as a function of reflectivity is a common user operation, and they expect theta to be deg.
- cc55089

2021-04-16 07:27 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
Not sure your parsing is correct (see equation 9 https://www.overleaf.com/9574295584nyybsdzmpbxd)

2021-04-16 07:29 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
I cannot access that without account.

2021-04-16 07:42 UTC, arm61 commented on src/ess/amor/amor.py
> +            sample_size (`sc.Variable`, optional): Size of the sample in direction of the beam. Optional, default `0.01 m`.
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

I think it needs this. I have always used google or numpy style so having `'sphinx.ext.napoleon'` is a given for me. If you are opposed I can change the style.

2021-04-16 07:43 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
[AMOR_Reduction-3.pdf](https://github.com/scipp/ess/files/6323345/AMOR_Reduction-3.pdf)

2021-04-16 08:14 UTC, arm61 commented on src/ess/reflectometry/__init__.py
> +G_ACC = -g * (sc.units.m / (sc.units.s * sc.units.s))
One thing this has made me realise is that I had negative gravity. Nice, accidental, catch (adding a test for this now)

2021-04-16 08:16 UTC, SimonHeybrock commented on src/ess/reflectometry/__init__.py
> +G_ACC = -g * (sc.units.m / (sc.units.s * sc.units.s))
Yet another reason for making it a vector?

2021-04-16 08:18 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
Your code does not seem to include the final term?

2021-04-16 08:32 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +    return ((sc.geometry.y(G_ACC) * (z_diff) * (z_diff) / (2 * velocity2)) - y_origin + y_measured) / (z_diff)
`sc.norm(G_ACC)`, in case someone changes the direction?

2021-04-16 08:36 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
The final term is 0, when z = z_0 (I haven't added this comment to the document just yet).

2021-04-16 08:38 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
Ok, but then I can't spot the difference between my equation and the one in the document (assuming `dz = z - z0`, etc.)?

2021-04-16 08:41 UTC, nvaytet reviewed
Some small comments

2021-04-16 08:41 UTC, nvaytet commented on .flake8
> +[flake8]
You can also add `flake8` flags to ignore certain lines or files in the files directly.
I don't think we have agreed on a standard way of doing things, but my opinion would be that it might be safer to not use a separate `.flake8` file, because someone might change the name of a file, or move it into a different subfolder, and then forget to change this file also?

2021-04-16 08:41 UTC, nvaytet commented on .flake8
> +    # line too long
For the long lines, I would say we should keep lines short, as enforced by `flake8`.
(one simple example is that it makes code much easier to review when lines don't go beyond the edge of the screen)
But we can discuss this. @SimonHeybrock what do you think?

2021-04-16 08:41 UTC, nvaytet commented on src/ess/amor/__init__.py
> +from ess.amor.amor import AmorData
We had something like `scipp.plot.plot` in the past, and we decided it was sometimes a little confusing, especially for novice python users. Maybe consider a different name for the `amor/amor.py` file?

2021-04-16 08:41 UTC, nvaytet commented on src/ess/amor/amor.py
> +        tof = buf.coords["tof"].astype(sc.dtype.float64) * 1e-3
This appears to assume some unit for the `"tof"` coord. Should there be a check, or maybe use a `to_unit` here?

2021-04-16 08:41 UTC, nvaytet commented on src/ess/reflectometry/__init__.py
> +from scipy.constants import neutron_mass, h, g
Don't we also have a neutron mass in scipp? Is it the same as is `scipy`?

2021-04-16 08:41 UTC, nvaytet commented on src/ess/reflectometry/data.py
> +                bins = np.linspace(q_z_vector.min(), q_z_vector.max(), 200)
I see `np.linspace` a number of times, and I also use it a lot. Sounds like adding a `sc.linspace` could be useful

2021-04-16 08:43 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Sorry this still isn't clear to me...

2021-04-16 08:49 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +            y_measured) / (z_measured - z_origin)
Grumble...it took me 2 hours to derive that equation from first principles, my brain was refusing to have it be so simply written 🤣

2021-04-16 08:55 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
Yeah, these functions were something that I was not really aware of until yesterday! Will try and put something together that uses them

2021-04-16 08:57 UTC, arm61 commented on .flake8
> +    # line too long
the long lines are exclusively in docstrings. I have found that line breaks in docstrings can have unexpected results in sphnix (I have always assumed this is why black and yapf don't touch docstrings).

2021-04-16 09:01 UTC, arm61 commented on src/ess/reflectometry/__init__.py
> +from scipy.constants import neutron_mass, h, g
Personally, think that HDM should be a `scippneutron` object that I can import.

2021-04-16 09:05 UTC, arm61 commented on .flake8
> +[flake8]
I agree about the `.flake8` file (I partly put it in cause the CI won't complete until flake8 is passed), however, I could only work out how to do this on a per line bases and I worry that the `# noqa: E501` would be considered part of the docstring by sphinx (see my point below)

2021-04-16 09:18 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
Issue with the `scattered_beam()` approach is that the function doesn't only use the vector from origin to measured but also uses both individually so the function would need all three arguments.

2021-04-16 09:21 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
Something like 
```
def angle_with_gravity(data, sample_to_pixel, sample_position, pixel_position):
    """
    Find the angle of reflection when accounting for the presence of gravity.

    Args:
        data (`scipp._scipp.core.DataArray`): Reduction data array.
        sample_to_pixel (`scipp._scipp.core.VariableView`): Vector of distance from sample to pixel, should be a `vector_3_float64`-type object.
        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
        pixel_position (`scipp._scipp.core.VariableView`): Detector pixel positions, should be a `vector_3_float64`-type object.

    Returns:
        (`scipp._scipp.core.Variable`): Gravity corrected angle values.
    """
    # This is a workaround until scipp #1819 is resolved, at which time the following should be used instead
    # velocity = sc.to_unit(HDM / wavelength, 'm/s')
    # At which point the args can be changed to wavelength
    # (where this is data.bins.constituents['data'].coords['wavelength'].astype(sc.dtype.float64) or similar)
    # instead of data
    velocity = sc.to_unit(
        HDM / data.bins.constituents["data"].coords["wavelength"].astype(
            sc.dtype.float64),
        "m/s",
    )
    data.bins.constituents["data"].coords["velocity"] = velocity
    velocity = data.bins.coords["velocity"]
    velocity.unit = sc.units.m / sc.units.s
    z_diff = sc.geometry.z(sample_to_pixel)
    y_diff = sc.geometry.y(sample_to_pixel)
    z_origin = sc.geometry.z(sample_position)
    y_origin = sc.geometry.y(sample_position)
    y_dash = y_dash0(velocity, z_diff, y_diff)
    intercept = y_origin - y_dash * z_origin
    y_true = sc.geometry.z(pixel_position) * y_dash + intercept
    angle = sc.to_unit(
        sc.atan(y_true / z_measured).bins.constituents["data"], 'deg')
    return angle
```
I am probably missing something that fresh eyes can help though

2021-04-16 09:23 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
My aim was to write this function (and all the functions in `corrections.py` and `resolution.py`) as that they can operate independently from the `DataArray` object.

2021-04-16 09:29 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +            sample_size (`sc.Variable`, optional): Size of the sample in direction of the beam. Optional, default `0.01 m`.
@OwenArnold @nvaytet Opinions?

2021-04-16 09:30 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
But shouldn't everything be translation invariant and not depend on actual positions? Why do you need absolute positions?

2021-04-16 09:34 UTC, SimonHeybrock commented on src/ess/reflectometry/__init__.py
> +from scipy.constants import neutron_mass, h, g
Yes, I have been thinking about adding physical constant for a while, we definitely should.

2021-04-16 10:27 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
A possible problem: if I use the same approach to mask theta and wavelength the previous mask is lost...(see line 332 onwards in `src/ess/reflectometry/data.py`

2021-04-16 10:30 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Hmm, what are the dimensions of your binned data? Can you show the html view before and after?

2021-04-16 10:31 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
There are cases where we need to apply masks when rebinning, I am not sure this is the case here, it might just be that the logic for that is too zealous.

2021-04-16 10:33 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Can you make sure to rebin the outer dimension first? So if you dims are `['theta', 'wavelength']` and you rebin first `wavelength` then `theta`, I think the `wavelength` mask cannot be preserved. But if you first rebin `theta` it should work (I hope :D).

2021-04-16 10:34 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
You can also do both dims at the same time. Or set the mask later. But in any case I would like to see exactly what you have, so I can double check that the logic does what it should.

2021-04-16 10:42 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
opps, I made a mistake actually. Different error now that I will deal with then call this resolved.

2021-04-16 10:53 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
This is now resolved, but the `q_bin()` method is a lot slower now (cause new dimensions have been added to the DataArray, I think).

2021-04-16 10:55 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
I need probably rewrite my maths to make it vector-based to get this to work in that framework.

2021-04-16 11:18 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
I need to think about what is happening there. Can you post screenshots of the input to `q_bin` and its output?

2021-04-16 11:29 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +                qzr = np.array(qzr)
- You are including masked events or bins here, is that intentional?
- What is the `ValueError` for? Empty bins?
- Is this the slow part you mention? If you have 3x as many bins I can well imagine a slowdown. I suppose this would be fixed if we add support for `binned.bins.coords['sigma_qz_by_qz'].bins.max()`?

2021-04-16 12:05 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
It also seems to break my `instrument_view`

2021-04-16 12:06 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
<img width="913" alt="Screenshot 2021-04-16 at 14 05 58" src="https://user-images.githubusercontent.com/15774281/115021901-e3557180-9ebc-11eb-8185-16b66c662e58.png">

This is a screenshot of the `DataArray`, the result is all 0s in the instrument view

2021-04-16 12:08 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
The first odd thing I notice is that you have `detector_id` as well as `theta` as dimensions? Shouldn't it typically be one or the other?

2021-04-16 12:09 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Did you bin in `theta` just to mask? If so, don't do that, instead compute a `detector_id`-dependent mask based on the theta of the detector.

2021-04-16 12:12 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
> This is a screenshot of the DataArray, the result is all 0s in the instrument view

Do you get some extra sliders for the extra dimensions? It may be that you are just viewing the first slice which contains no events.

2021-04-16 12:18 UTC, arm61 commented on src/ess/amor/amor.py
> +        buf.coords["tof"] = tof
Spoke to the AMOR scientist, this is related to the `event_time_offset` being from the pulse generator at SINQ and therefore the AMOR `tof` is not the same. He is confident that this is the correct maths to normalise it.

2021-04-16 12:19 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
theta is a event object cause of the gravity correction

2021-04-16 12:20 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
There are lots more sliders than there should be but all slices are either nan or 0

2021-04-16 12:21 UTC, arm61 commented on src/ess/reflectometry/data.py
> +                qzr = np.array(qzr)
Not intentional, just not clear how best to to this. Ideally a `binned.bins.coords['sigma_qz_by_qz'].bins.max()` function that did if for me 🙂

2021-04-16 12:21 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
So you are saying: While events from the same detector are detected a the same theta, their actual theta is something else? Do we still need the `detector_id` dimension then? It feels slightly confusing (at least when thinking about it initially), but maybe you do need it?

2021-04-16 12:22 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +                qzr = np.array(qzr)
Ok, will put it on the TODO list.

2021-04-16 12:23 UTC, nvaytet commented on .flake8
> +[flake8]
See e.g. here to apply it to the entire file: https://github.com/scipp/scipp/blob/main/python/src/scipp/__init__.py#L6
I think you can also add an error code so that it only ignores selected types of errors

2021-04-16 12:40 UTC, arm61 commented on .flake8
> +[flake8]
I tried this for selected error types yesterday but couldn't get it to work.

2021-04-16 12:43 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Once I find theta, I don't think I need `detector_id`, but I imagine it is necessary for things like `instrument_view`?

2021-04-16 12:45 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
The question is: do you still need the instrument view at that point? As far as I understand it is mainly used for visualizing the raw data, but the more we proceed with data reduction the more we would use other visualization options.

2021-04-16 12:48 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
That would involve having >1 `DataArray` which is additional complexity.

2021-04-16 12:50 UTC, SimonHeybrock commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Not sure I understand. Maybe we should have a call next week to chat about this and similar things?

2021-04-16 12:53 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
Yeah there is a disconnect somewhere I think 🤣. I will send you a meeting thing.

2021-04-19 11:21 UTC, OwenArnold requested changes
Nice work! great to see how you're making use of scipp.

2021-04-19 11:21 UTC, OwenArnold commented on src/ess/reflectometry/data.py
> +            sigma_theta_position = (angle_max - angle_min) / 2.354820045
What is this hard-coded value used in the division?

2021-04-19 11:21 UTC, OwenArnold commented on src/ess/reflectometry/data.py
> +    The general reflectometry data class.
Until we know it's generic, and have multiple reflectometers I think it probably makes sense to keep everything under `reflectometry` in the `amor` directory. That way we can enforce a simple structure in ess `src/ess/{instrument}`. We have followed this approach with the wavelength-frame-multiplication, which is for the  `v20` instrument only at present, but will in principle be fully generic.

2021-04-19 11:21 UTC, OwenArnold commented on tests/reflectometry/corrections_test.py
> +        assert_almost_equal(
No major problem with this, but scipp also provides `isclose` `identical` and a range of other comparison functions you can use without having to decompose your variables.

2021-04-19 12:09 UTC, arm61 commented on src/ess/reflectometry/data.py
> +    The general reflectometry data class.
Personally (in part, cause I don't wanna refactor now to put it all in `amor` just to refactor back in X years time when ESTIA and then FREIA are using the code), I think that having this structure "defined" as the general class makes it more likely that this class will be used in future.

2021-04-19 12:10 UTC, arm61 commented on tests/reflectometry/corrections_test.py
> +        assert_almost_equal(
I thought this may be the case, but I wasn't aware of them/am comfortable in NumPy.

2021-04-19 12:12 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +    The general reflectometry data class.
I think I agree with Andrew here (since this is an ESS library): Putting this into `reflectometry` makes it *more* likely that we will end up with common code between instrument, since no one will want to dig through some instrument folders to find functionality. If this was something going into `scippneutron.reflectometry` I would agree with @OwenArnold, but I think this would be a much later step.

2021-04-19 13:25 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
I have reverted to the original masking for now. I reckon we should still chat (my plan from this morning didn't pan out when I thought harder about it).

2021-04-19 13:41 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +        sample_position (`scipp._scipp.core.VariableView`): Scattered neutron origin position.
The absolute positions are needed for the resolution function stuff (cause the sample position is not necessarily where the beam was scattered from). The only way to achieve this code with the`scn.scattered_beam()` would involve overwriting the `sample_position` attribute.

2021-04-19 13:46 UTC, arm61 commented on .flake8
> +[flake8]
I got this working in the end

2021-04-21 09:04 UTC, arm61 commented on src/ess/amor/amor.py
> +                self.data.bins.coords["wavelength"] > wavelength_max)
This has been fixed now I think

2021-04-21 09:06 UTC, arm61 commented on tests/reflectometry/corrections_test.py
> +        assert_almost_equal(
I will gradually adapt the tests to scipp tests over time.

2021-04-21 09:11 UTC, arm61 commented
In my opinion, the code is now feature complete. Just getting the last tests in place today then I think I am ready.

2021-04-21 09:22 UTC, OwenArnold commented on tests/reflectometry/corrections_test.py
> +        assert_almost_equal(
Yes, I'm ok with that.

2021-04-21 09:23 UTC, OwenArnold commented on src/ess/reflectometry/data.py
> +    The general reflectometry data class.
The new contributing guidelines for the repo should make things a bit clearer after we had an internal discussion. But we are in agreement that having the `reflectometry` directory is OK.

2021-04-21 11:28 UTC, arm61 commented
That's test coverage back at 100 %.

2021-04-22 08:40 UTC, SimonHeybrock commented on tests/reflectometry/resolution_test.py
> +np.random.seed(1)
Hmm, maybe not a good idea at file scope? Not sure what this affects if `pytest` runs multiple files? Where is it even used below?

2021-04-22 08:48 UTC, SimonHeybrock commented on src/ess/amor/amor_data.py
> +        supermirror_min_q = ((0.022) * self.event.coords['qz'].unit)
Magic number?

2021-04-22 08:48 UTC, SimonHeybrock commented on src/ess/amor/amor_data.py
> +                    1.0 - (0.25 / 0.088) * (self.event.coords['qz'].values[
Magic number?

2021-04-22 08:50 UTC, SimonHeybrock commented on src/ess/amor/amor_data.py
> +    def q_bin(self, bins=None, unit=(1 / sc.units.angstrom).unit):
```suggestion
    def q_bin(self, bins=None, unit=sc.Unit('1/angstrom')):
```
may be nicer

2021-04-22 08:50 UTC, arm61 commented on tests/reflectometry/resolution_test.py
> +np.random.seed(1)
Lazy copy-paste

2021-04-22 09:04 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +    scale_factor = erf((sample_size / beam_on_sample * fwhm_to_std).values)
Just to double check, is this doing what you want to? As it is written it computes
```python
(sample_size / beam_on_sample) * fwhm_to_std
```
is that what you meant?

2021-04-22 09:05 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +        #                          dims=theta.dims) * sample_size
commented code?

2021-04-22 09:09 UTC, SimonHeybrock commented on src/ess/reflectometry/corrections.py
> +                                      dims=theta.dims)
Is the explicit broadcast required? Since scipp operation broadcast automatically, does it work with just `beaom_on_sample = sample_size`?

2021-04-22 09:09 UTC, arm61 commented on src/ess/reflectometry/corrections.py
> +    scale_factor = erf((sample_size / beam_on_sample * fwhm_to_std).values)
Yeah that is correct.

2021-04-22 09:12 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +                scatter=True).bins.constituents["data"].coords["wavelength"])
Is there a reason why this is done by hand, rather than as:
```python
self.data = scn.convert(self.data, "tof", "wavelength", scatter=True)
```
Is it simply to also keep the `tof` coord?

2021-04-22 09:17 UTC, arm61 commented on src/ess/reflectometry/data.py
> +                scatter=True).bins.constituents["data"].coords["wavelength"])
real answer: I am daft and didn't realise it would work in that way. 

That said, keeping `tof` is useful.

2021-04-22 09:18 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +                scatter=True).bins.constituents["data"].coords["wavelength"])
We can consider providing an option for preserving the input coord.

2021-04-22 09:20 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +                "sigma_theta_by_theta"] = sigma_theta.bins.constituents["data"]
Not now, but we should look into whether we can handle some of these as coord/attrs with variances.

2021-04-22 09:23 UTC, arm61 commented on src/ess/reflectometry/data.py
> +                "sigma_theta_by_theta"] = sigma_theta.bins.constituents["data"]
I will make a note of this.

2021-04-22 09:44 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +        self.data.masks["z_mask"] = (z_position < z_min) | (z_position > z_max)
```python
no_mask = sc.scalar(True)
mask = x_position == x_position
self.data.masks['x'] = mask
self.data.masks['y'] = mask
self.data.masks['z'] = mask
a['x', x_min:x_max].masks['x'] &= no_mask
a['y', y_min:y_max].masks['y'] &= no_mask
a['z', z_min:z_max].masks['z'] &= no_mask
```
Nicer? Yes, this should work even if you have `None` for some of the inputs.

2021-04-22 09:45 UTC, SimonHeybrock commented on src/ess/reflectometry/data.py
> +        self.data.masks["z_mask"] = (z_position < z_min) | (z_position > z_max)
No, sorry, scratch that, this would only work if you had separate `x`, `y`, and `z` coords. Leave it as it is.

2021-04-22 10:01 UTC, SimonHeybrock approved these changes
Nice work for a "first draft" 👍 

I assume there will be many more changes in the future, but I don't see anything wrong with merging this now.

2021-04-22 10:01 UTC, merged

2021-04-22 10:02 UTC, arm61 commented
🎉 🎉 🎉