Create contributing.md
scipp/ess-legacy-v2 pull request #16
Opened 2021-04-19 11:47 UTC by OwenArnold

Welcome contributions and set some simple guidelines.

2021-04-20 09:41 UTC, SimonHeybrock commented on contributing.md
> +This repository is ess instrument centric and we therefore strongly prefer having all code organised into `src/ess/{instrument}` directories. If your code is specific to the ess facility, but is inte
Remember our guideline of one line per sentence, for diff readability.

2021-04-20 09:46 UTC, nvaytet requested changes
- I think we need to add all folders: `reflectometry`, etc.
- I would also add instrument folders

2021-04-20 09:46 UTC, nvaytet commented on contributing.md
> +We welcome contributions to this repository. When contributing to this repository, we encourage you to discuss the change you wish to make via issue, email, or any other method with the owners of thi
Can we have one sentence per line if possible?
Makes it easier to edit/review.

2021-04-20 09:46 UTC, nvaytet commented on contributing.md
> +Please provide and update documentation. Put python docstrings on your user facing functions, provide code comments and consider other explanations you need to provide to desribe how your functions w
```suggestion
Please provide and update documentation. Put python docstrings on your user facing functions, provide code comments and consider other explanations you need to include to describe how your functions work. We will build and publish sphinx documentation located [here](https://github.com/scipp/ess/tree/main/docs).
```

2021-04-20 09:48 UTC, nvaytet commented
I would vote for one spectroscopy directory

2021-04-20 10:48 UTC, OwenArnold commented
> * I think we need to add all folders: `reflectometry`, etc.
As per the pr description, I'm not sure of the best way of organising this for all techniques.

2021-04-20 10:59 UTC, nvaytet reviewed
Missing dirs?
`beer`, `freia`, `bifrost`, `cspec`

2021-04-20 10:59 UTC, nvaytet commented on contributing.md
> +If your code is specific to the ess facility, but is intended to be ubiquitous across a class of instruments, you may put it into a technique specfic directory `src/ess/{technique}` i.e `src/ess/refl
```suggestion
If your code is specific to the ess facility, but is intended to be ubiquitous across a class of instruments, you may put it into a technique specific directory `src/ess/{technique}` i.e `src/ess/reflectometry`.
```

2021-04-21 09:13 UTC, nvaytet approved these changes
Looks good now.
We have to be careful with keeping this repo clean, as there will probably be many contributors.
For instance, after this is merged we would have a `imaging` folder, but we also have a `v20/imaging` folder.

2021-04-21 09:16 UTC, nvaytet commented
Although, should we not have at least a reflectometry folder so that @arm61 can put his files in the right places?

2021-04-21 09:18 UTC, OwenArnold commented
> Although, should we not have at least a reflectometry folder so that @arm61 can put his files in the right places?

We should, I'm avoiding potential conflict by not making it as I know it's coming from his PR.

2021-04-21 09:19 UTC, OwenArnold commented
> We have to be careful with keeping this repo clean, as there will probably be many contributors.

Fully agree.

2021-04-21 09:19 UTC, merged