add custom amor q grid function
scipp/ess-legacy-v2 pull request #23
Opened 2021-04-27 06:52 UTC by arm61

Following some feedback from that Amor instrument scientist, I have added a custom grid definition function as a helper function. 

Currently this returns a NumPy array, but in future this will be converted to a `scipp` object (see #22).

2021-04-27 13:15 UTC, nvaytet commented on src/ess/amor/amor_data.py
> +def q_grid(q_min=0.008, q_fix=0.005, q_max=0.08, d_q=None):
It seems like this should maybe move to a different place than `amor_data.py`, which until now seems to contain classes that hold data.
This is more like a tool or utility?
And the amor_data file is starting to get quite long.

2021-04-27 14:10 UTC, arm61 commented on src/ess/amor/amor_data.py
> +def q_grid(q_min=0.008, q_fix=0.005, q_max=0.08, d_q=None):
This is a very good comment. Split it out a bit now.

2021-04-29 07:57 UTC, arm61 commented
I think it is best to merge this before dealing with #22. So that this is available to the scientist soon while the stuff in https://github.com/scipp/scipp/pull/1871 makes its way to a release. Thoughts?

2021-05-03 09:49 UTC, arm61 commented
This has been rebased and added a bug fix that effected the testing on the DMSC infrastructure.

2021-05-03 10:42 UTC, arm61 commented
@nvaytet if there are no issues can this be merged in. Then I will start on #22

2021-05-05 08:53 UTC, nvaytet commented
The last thing I wanted to check with the rest of the scipp team was the formatting rules.
I see you are just disabling some flake8 checks at the top of your files.
Our feeling is that we shouldn't disable checks if it is not necessary, but we also see that the 80 character limit is a bit painful to work with.
But we never came to a firm conclusion. I will ask again and see if we can come up with something fast.

2021-05-05 12:01 UTC, nvaytet commented
For now, could you check what the docs would look like if you made the lines fit inside the 79char limit?
I would rather only disable flake8 checks in `__init__.py` files, because I think the more people start contributing, the more messy it's going to get if people just realise "oh i can just disable flake8" and push all sorts of ugliness in the repo.

2021-05-07 06:12 UTC, arm61 commented
So the issue arises if you need the line break in the type definition of the doctoring, i.e. below I put a line break before the word `optional` (which is column like 78 or somthing) in https://github.com/scipp/ess/blob/d0da21ff22989f6f65c4fd67aa912923cdecd163/src/ess/reflectometry/data.py#L28

![Screenshot 2021-05-07 at 08 09 53](https://user-images.githubusercontent.com/15774281/117405262-a1dc4300-af0b-11eb-83ad-9d583f99f74e.png)

2021-05-07 06:27 UTC, arm61 commented
If the issue of ugliness not dealt with by `yapf` anyway?

2021-05-07 20:47 UTC, nvaytet commented
Hmm so why don't i see the issue in e.g. the `plot` function's docstring? https://github.com/scipp/scipp/blob/main/python/src/scipp/plotting/__init__.py#L79
![Screenshot at 2021-05-07 22-47-37](https://user-images.githubusercontent.com/39047984/117506659-426f4900-af86-11eb-926d-f7a87dc5346f.png)

2021-05-07 20:49 UTC, nvaytet commented
Maybe because of the different syntax we are using for the docstring?

2021-05-10 07:01 UTC, arm61 commented
You might be right, but changing all of the docstrings is a big task. I have opened an issue for it so I don't forget (https://github.com/scipp/ess/issues/26).

2021-05-10 09:56 UTC, nvaytet commented
> You might be right, but changing all of the docstrings is a big task. I have opened an issue for it so I don't forget (#26).

Ok, just remember to add as a task on that PR to remove the lines that disable some `flake8` checks.

2021-05-10 09:58 UTC, nvaytet commented
Also remember to add the license identifier (BSD3) at the top of your files.
Don't know if you want to do that here or when you change the docstrings.

2021-05-11 09:12 UTC, arm61 commented
I have added the licence file this time so that I don't forget!

2021-05-11 14:19 UTC, nvaytet requested changes

2021-05-11 14:19 UTC, nvaytet commented on tests/amor/tools_test.py
> +# flake8: noqa: E501
I'm really sorry for being a pain, 🙏 but we also have license identifiers/headers in the test files.

2021-05-15 09:57 UTC, arm61 commented on tests/amor/tools_test.py
> +# flake8: noqa: E501
My bad!

2021-05-19 09:02 UTC, nvaytet approved these changes

2021-05-19 09:02 UTC, merged