Unit testing wfm
scipp/ess-legacy-v2 pull request #38
Opened 2021-07-01 15:03 UTC by OwenArnold

* Support easier refactoring for more instruments ODIN imminent 
* Catch issues as scipp/scippneutron evolves
* Share more knowledge about WFM
* Catch bugs and opportunities for improvements

2021-07-07 08:04 UTC, SimonHeybrock commented on src/ess/v20/wfm/frames_analytical.py
> +            kwargs = {'unit': sc.units.us}
Hard-coded unit?

2021-07-07 08:16 UTC, nvaytet requested changes

2021-07-07 08:16 UTC, nvaytet commented on src/ess/v20/wfm/frames_analytical.py
> +        def make_edge(dims, x):
```suggestion
        def _make_edge(dims, x):
```

2021-07-07 08:16 UTC, nvaytet commented on src/ess/v20/wfm/frames_analytical.py
> +            pos_norm.dims,
use keyword args?

2021-07-07 08:16 UTC, nvaytet commented on src/ess/v20/wfm/frames_analytical.py
> +            pos_norm.dims,
use keyword args?

2021-07-07 08:16 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    # Arbitrary pulse length of 10us in duration
it seems there is no default 10us set in the function def.
where does the number come from?

2021-07-07 08:16 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +def _single_chopper_double_window(window_opening_t,
Can some of the code from the single and double windows be made common to reduce duplication?

2021-07-07 08:16 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    # Following results best understood sketching simple time-distance
I think this is a really weird setup to have
![Screenshot at 2021-07-07 10-05-14](https://user-images.githubusercontent.com/39047984/124723145-0404f480-df0b-11eb-8e9e-186dc9ac1610.png)
you have neutrons that are traveling back in time...
I would say we should change the phase, and maybe the pulse length, so we can get something that is realistic.

2021-07-07 08:16 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    for offset in [0.0 * sc.units.us, 5.0 * sc.units.us]:
5us is the same offset as the previous test, so we are not testing anything new here?

2021-07-07 08:16 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +        frames['right_edges'].data.values[1])
Ideally, it would also be good to have a test with 2 WFM choppers, since this will probably be the norm, and make sure the shifts are computed at the mid-point between the choppers.

2021-07-07 08:28 UTC, nvaytet commented
However, good to see you didn't have to do many changes for a new beamline!

2021-07-11 20:21 UTC, OwenArnold commented on tests/v20/wfm/frames_analytical_test.py
> +    # Following results best understood sketching simple time-distance
Yes, I did this deliberately as the symmetry seems to be the easiest way to reason what is happening without having full time-distance diagrams generated for the unit tests. I think this simplicity is reasonable given that this is at the unit-test level, but we would never want to expose/describe at the top-level. In fact, we should probably sanitise inputs at the `get_frames` level to ensure that calculated times cannot be negative and that the velocities cannot be negative. I'm open to suggestions on improving this, provided that maintainers can easily figure things out without schematics.

2021-07-12 16:06 UTC, OwenArnold commented on tests/v20/wfm/frames_analytical_test.py
> +    # Arbitrary pulse length of 10us in duration
Comment left over after refactoring

2021-07-20 14:48 UTC, nvaytet requested changes

2021-07-20 14:48 UTC, nvaytet commented on src/ess/v20/wfm/stitch.py
> +def items(x):
I don't see where this is being used.

2021-07-20 14:48 UTC, nvaytet commented on tests/reflectometry/test2.txt
> +# hello
I don't see this file being used anywhere?

2021-07-20 14:48 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    assert sc.all(b['left_edges'].data > a['left_edges'].data).value
```suggestion
    assert allclose(b['left_edges'].data, a['left_edges'].data + 1.0 * sc.units.us).value
```
and the same for the lines below?

2021-07-20 14:48 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    padding = 1.0 * sc.units.us
Could you explain what you mean by padding here?

2021-07-20 15:21 UTC, OwenArnold commented on tests/v20/wfm/frames_analytical_test.py
> +    padding = 1.0 * sc.units.us
absolute time between the pulse finishing and the chopper opening in example. Otherwise the gradients result in division by zero. I have tried to minimise changes to wfm code itself.

2021-07-20 15:22 UTC, OwenArnold commented on tests/reflectometry/test2.txt
> +# hello
Added by mistake. I need to merge master. I've already made the fix to stop Andrew's code from producing these outputs in the source directory.

2021-07-20 15:23 UTC, OwenArnold commented on src/ess/v20/wfm/stitch.py
> +def items(x):
👍 I still need to wire this in. Will do.

2021-07-21 11:14 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    padding = 1.0 * sc.units.us
Add this as a comment?

2021-07-21 12:56 UTC, OwenArnold commented on tests/v20/wfm/frames_analytical_test.py
> +    padding = 1.0 * sc.units.us
The function that uses it now has a renamed argument so it should be clearer.

2021-07-21 14:57 UTC, nvaytet requested changes
Also, I still don't see the `items` being used.

2021-07-21 14:57 UTC, nvaytet commented on tests/v20/wfm/frames_analytical_test.py
> +    assert sc.all(b['right_edges'].data > a['right_edges'].data).value
`allclose` here also?

2021-07-22 08:15 UTC, nvaytet approved these changes

2021-07-22 08:19 UTC, merged