Imaging loaders should handle directory of FITS files
scipp/ess-legacy-v2 pull request #4
Opened 2021-01-05 10:15 UTC by OwenArnold

As well as TIFF files currently handled

2021-01-05 12:30 UTC, nvaytet requested changes

2021-01-05 12:30 UTC, nvaytet commented on ess/v20/imaging/helper_funcs.py
>  from tifffile import imsave
i wonder why you need both `fabio` and `tifffile`? Can't you read the tiffs also with `tifffile`?

2021-01-05 12:30 UTC, nvaytet commented on ess/v20/imaging/helper_funcs.py
> +def fits_to_variable(fits_dir, dtype=np.float64, with_variances=True):
Remove duplicate code between `tiffs_to_variable` and `fits_to_variable` by making a generic function called by both?

2021-01-05 14:24 UTC, OwenArnold commented on ess/v20/imaging/helper_funcs.py
>  from tifffile import imsave
I think so. There is some history here I don't recall, but I would definitely be in favour of dropping one.

2021-01-05 14:25 UTC, OwenArnold commented on ess/v20/imaging/helper_funcs.py
> +def fits_to_variable(fits_dir, dtype=np.float64, with_variances=True):
I had thought to do that, I think we should do this.

2021-01-06 09:16 UTC, nvaytet approved these changes

2021-01-06 09:52 UTC, merged