Generalize and cleanup WFM stitching to allow for ODIN
scipp/ess-legacy-v2 pull request #42
Opened 2021-08-04 08:53 UTC by nvaytet

- New method to determine frame edges based on https://www.sciencedirect.com/science/article/pii/S0168900220308640
- Store the chopper information in the dataset as a `choppers` coordinate, which contains a Dataset
- Separate plotting of time-distance diagram into a new function which accepts the dataset as input (this now calls `get_frames` internally)
- Allow `stitch` to return either a single DataArray where all frames are rebinned into the same tof bins (original behaviour) or return a dict of DataArrays which contain the individual frames (use `merge_frames=False`).

2021-08-09 20:47 UTC, nvaytet commented
@OwenArnold I think this is ready for review now.
I've added some release notes (there wasn't actually a file for them).
I will add a docs notebook on how to use the WFM stuff in a second step.

2021-08-10 11:37 UTC, OwenArnold requested changes
There are some other parts I still need to take a detailed look at.

* Looks much cleaner than what we had before and easier to understand
* Good use of reference for the calculations
* Good structure with instruments providing the bespoke parts and a common WFM framework
* Good use of scipp in the updates

2021-08-10 11:37 UTC, OwenArnold commented on docs/about/release-notes.rst
> +Since v0.4
since v0.0.4

FYI I think this next release should correspond to `v0.1`

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/odin/beamline.py
> +        "WFMC1":
One of our discussion items was whether the naming here is good I think. Didn't we discuss having some indirection to access particular sets of choppers that would not rely on the naming? Maybe an inner dictionary/list containing the name of corresponding keys would be helpful, or maybe we nest the choppers under "WFM", "FOC", "BPC" keys?

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/odin/beamline.py
> +        Chopper(frequency=sc.scalar(56.0, unit=hz),
👍  this looks unambiguous. Do we need to make additional TDC considerations, or is this all wrapped in the phase?

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/odin/beamline.py
> +                # values=[81.12, 127.82, 171.60, 212.66, 251.16, 287.50],
Remove dead code

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/odin/beamline.py
> +    Note that there is a typo in the paper for the FOC1 opening angles.
Might be useful to say a bit more about what the typo is exactly so easier to track down in future

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/v20/imaging/beamline.py
> +                values=np.array([83.71, 140.49, 193.26, 242.32, 287.91, 330.3]) + 15.0,
Where does +15 come from? maybe add comment

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +# class Beamline:
Dead code remove

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +    alpha = 2.5278e-4 * (sc.Unit('s') / sc.Unit('angstrom') / sc.Unit('m'))
Should say that this is neutron mass divided by planks constant (as a comment) or better yet define alpha from those.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +def make_fake_beamline(
Why does this live in the working code rather than being part of the tests?

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +        pulse_length=sc.scalar(2.86e-03, unit='s'),
source pulse length. Would help with the mental model below if this was named as such.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +        pulse_t_0=sc.scalar(1.3e-4, unit='s'),
source pulse t0 (start of source pulse)

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +        frequency=sc.scalar(56.0, unit=sc.units.one / sc.units.s),
WFM chopper(s) frequency

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +        chopper_positions={
Assumes source chopper at origin (quite important in following calculations)

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +        phi_wfm_1 = omega * (
Could we have better names or just comments for these so that one does not keep having to cross reference to paper. Alternatively you could refer to the equation in the paper for each of these.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +    dim = 'frame'
```suggestion
    dim_frame = 'frame'
```
Helps with readability further down

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +# def make_coords(**kwargs):
Remove dead code

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/choppers.py
> +            array = sc.concatenate(array, scalar, dim)
Is this ever reached? `array=None` on line 33.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +    TODO: This currently ignores scattering paths, only the distance from
Good point.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +    # Now find frame boundaries
Tweak comment - Initialise entries for the frame edges. Finding happens below.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +    frames["left_edges"] = sc.zeros(dims=["frame"] + data.meta["position"].dims,
Maybe have the names for this more verbose. Could easily be thought of as the angle of the left edge of a cutout in radians.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +    pos_norm = sc.norm(data.meta["position"])
Could you include pixel in the name for this variable. Helps further down.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/plot.py
> +    """
Maybe say something about what the expected `data` argument is. i.e. this i the beamline + chopper information.

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/plot.py
> +    return fig
An orthogonal comment - we don't handle the BPC at all either in the frame calculations or the diagrams. Maybe that's something we should do in future as the paper describes their use for skipping pulses (7Hz operation)

2021-08-10 11:37 UTC, OwenArnold commented on src/ess/wfm/tools.py
> +
I think we said we were going to use the plot utilities (from scipp) implementation of these when we get a new scipp release - maybe mark as a todo.

2021-08-10 12:25 UTC, nvaytet commented on src/ess/wfm/beamline.py
> +    alpha = 2.5278e-4 * (sc.Unit('s') / sc.Unit('angstrom') / sc.Unit('m'))
This is exactly the comments that are above?

2021-08-10 12:26 UTC, nvaytet commented on src/ess/wfm/beamline.py
> +def make_fake_beamline(
I wanted to use it in notebooks for the docs, and not sure how to import it if it is in the tests.
I also thought this might have been what the Odin people were after: a tool to create a chopper cascade from user-defined requirements?

2021-08-10 12:28 UTC, nvaytet commented on src/ess/wfm/beamline.py
> +        phi_wfm_1 = omega * (
I'll reference the equations

2021-08-10 12:30 UTC, nvaytet commented on src/ess/wfm/tools.py
> +
I don't know how to make a good time-distance diagram with the scipp plotting.
I think it needs to be done manually with matplotlib.

2021-08-10 13:20 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +    alpha = 2.5278e-4 * (sc.Unit('s') / sc.Unit('angstrom') / sc.Unit('m'))
Yes sorry you're right.

2021-08-10 13:22 UTC, OwenArnold commented on src/ess/wfm/tools.py
> +
I'm referring to the `to_bin_centers`, `to_bin_edges` general functions below. Not the plotting with is clearly bespoke to the time-distance-diagrams.

2021-08-10 13:35 UTC, OwenArnold commented on src/ess/wfm/beamline.py
> +def make_fake_beamline(
I think the desire would be to output the chopper cascade positions rather than take it as part of the argument set. i.e. given the wavelength resolution.

Good point about the notebooks. Can we at least put this into another examples modules? It seems out of place where it is.

2021-08-10 13:40 UTC, OwenArnold commented on src/ess/wfm/tools.py
> +    return t_open, t_close
Again probably orthogonal to this, but I wonder if some of the common chopper functionality should be separated from WFM itself. Candiates might include.

* the two functions above relating to chopper times and angles
* calculations that determine neutron velocity/time from wavelenth
* time_distance_diagram

I don't see a need for this at present, but it could be something we want when we start working with direct-inelastic instruments (among others).

2021-08-10 17:53 UTC, nvaytet commented on docs/about/release-notes.rst
> +Since v0.4
yes i can see that we never made a release. However, git describe gives `0.4`, not sure i understand why.

2021-08-10 17:54 UTC, nvaytet commented on src/ess/odin/beamline.py
> +        Chopper(frequency=sc.scalar(56.0, unit=hz),
It's all in the phase and the opening angles.

2021-08-11 06:31 UTC, nvaytet commented on src/ess/odin/beamline.py
> +        "WFMC1":
Yes, I had tried to address this by adding an argument to the `frames_analytical` function (https://github.com/scipp/ess/blob/06b36a32db309294a4d5723e378889a810ac4c9a/src/ess/wfm/frames_analytical.py#L10) but I don't really like it.

Now I am thinking of adding a `kind` field to the `Chopper` class, which would just be an `Enum`, and using that to identify the WFM choppers. What do you think?

2021-08-11 07:23 UTC, OwenArnold commented on src/ess/odin/beamline.py
> +        "WFMC1":
Sounds good. Presumably once we know that two choppers are WFM we don't need to know which is the second or the first, either because we are averaging the position, or because we can just use distance from the source to determine which is which?

2021-08-11 08:29 UTC, nvaytet commented on src/ess/odin/beamline.py
> +        "WFMC1":
Yes, I am already using the distance to do this: https://github.com/scipp/ess/blob/06b36a32db309294a4d5723e378889a810ac4c9a/src/ess/wfm/frames_analytical.py#L54

2021-08-11 20:21 UTC, nvaytet commented on src/ess/wfm/beamline.py
> +        chopper_positions={
I don't think this assumes anything about the source. Differences between source position and chopper positions are taken further along the workflow.

2021-08-11 20:35 UTC, nvaytet commented on src/ess/wfm/beamline.py
> +    dim = 'frame'
I don't see any other `dim` in that function or file, so i left it as is.

2021-08-11 20:36 UTC, nvaytet commented on src/ess/wfm/plot.py
> +    return fig
Yes, but we are only ever plotting a single pulse, so I think it's fine for now.

2021-08-11 20:37 UTC, nvaytet commented on src/ess/wfm/tools.py
> +    return t_open, t_close
I think maybe your concerns here were partially solved by refactoring the `Chopper` to do the angle+frequency -> opening times conversion etc.. ?

2021-08-12 09:00 UTC, nvaytet commented on src/ess/v20/imaging/beamline.py
> +                values=np.array([83.71, 140.49, 193.26, 242.32, 287.91, 330.3]) + 15.0,
Done in the functions's docstring

2021-08-12 09:01 UTC, nvaytet commented on src/ess/wfm/beamline.py
> +def make_fake_beamline(
Not sure where else to put it.... any suggestions?

2021-08-12 09:02 UTC, nvaytet commented on src/ess/wfm/frames_analytical.py
> +    frames["left_edges"] = sc.zeros(dims=["frame"] + data.meta["position"].dims,
yes i renamed everything. `left_edges` and `right_edges` are now `time_min` and `time_max`

2021-08-17 11:19 UTC, nvaytet commented
@OwenArnold I managed to speed up the time-consuming step by using a mask to discard the invalid neutrons.
Can you have another look at this? Thanks!

2021-08-18 08:49 UTC, OwenArnold approved these changes
Some minor comments but those could be addressed in a follow up if required.

2021-08-18 08:49 UTC, OwenArnold commented on src/ess/wfm/choppers.py
> +        self._opening_angles_center = opening_angles_center
We don't have a docstring or otherwise to explain that not all of these inputs are mandatory and that they can generate conflict if they do not match.

2021-08-18 08:49 UTC, OwenArnold commented on tests/wfm/chopper_test.py
> +    with pytest.raises(ValueError) as e_info:
Minor. You might consider adding custom exceptions for some of the failure modes in the `Chopper` this is probably as many lines of code as we have already, and then we don't rely on fragile text based matching.

2021-08-18 08:49 UTC, merged