Add wfm intro notebook
scipp/ess-legacy-v2 pull request #43
Opened 2021-08-14 07:56 UTC by nvaytet

Add notebook to docs as intro to WFM.

2021-08-17 10:40 UTC, OwenArnold requested changes
I've focused on the text rather than the graphics. Between the new notebooks, I think this is really good.

I can see that the basics notebook would be great to onboard developers, along those lines, for the WFM basics I wonder if it's a good idea to include an appendix of some basic concepts/calculations/proofs such as the de Broglie wavelength. Might be overkill though.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "This also means that the resolution can be pretty poor for a long-pulsed source such as the ESS.\n",
```suggestion
    "This also means that the resolution is poor for a long-pulsed source such as the ESS compared to their short-pulse counterparts, such as ISIS.\n",
```

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "This has the effect of merging many different wavelengths together on the same detector pixel,\n",
Can we reword this. Maybe something along the lines of:

The problem cannot be resolved at the detector. According to the difference between time recorded at the detector and the measured start of the source pulse, both neutrons have the same wavelength. The detector recording system has no way of knowing that this is not the reality or adjusting for this. We instead look at the pulse generation to find ways to better measure the wavelength of our neutrons.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "The main reason for using the WFM concept is to redefine the burst time $t_{P} = \\Delta t$ as implied by Eq. (1), in order to match the required wavelength resolution of the experiment."
A secondary objective, (or constraint of the first) is to utilise as much of the source pulse as possible.

Side discussion. As you improve reduce dLam/Lam you trade off flux. I'm not sure if you go on to derive or discuss those considerations. - My initial guess is that you can derive this as a function of the intersection of t_opening for both choppers as a ratio of the inverse chopper frequency.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "Here we define several important quantities:\n",
You might want to say that FOCs (not yet introduced) control  introduce filtering to limit the neutrons to fall between `t0`, `tA` after they pass through the WFM chopper system.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "### Using a single WFM chopper\n",
👍  for logically working through the chopper system like this. It can get confusing when we consider the whole cascade rather than the choppers one by one.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "Because $\\Delta t$t is independent of the wavelength for the case of a single WFM chopper disc,\n",
`$\\Delta t$t` ?

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "$t(\\lambda) = \\alpha \\lambda z_{\\rm det}$ to $t(\\lambda) = \\alpha \\lambda (z_{\\rm det} - z_{\\rm WFM})$.\n",
Assuming straight-line WFM-Detector via source. I think introducing the source into this is too complex, but the reader might wonder why we omit it.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "where a constant $\\Delta \\lambda / \\lambda$ is much more desirable.\n",
Because, of limitations of the detector and timing systems, or some other physical features? Maybe Soren could add something to explain this.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "In this context, 'optically blind' indicates that the choppers have the same opening angles,\n",
Is this true. Do they have to have the same opening angles to be optically blind. I seem to recall the V20 choppers not being duplicate choppers with a phase offset (in design)

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "The concept of wavelength frame multiplication implies that no data can be recorded in the\n",
Fundamental requirement by design rather than something we imply. Do you want to mention that this is prior to stitching to distinguish the fact that once stitching occurs we do indeed expect overlap?

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "They are designed such that $\\lambda_{N, {\\rm max}} = \\lambda_{N+1, {\\rm min}}$ yield a continuous spectrum\n",
```suggestion
    "They are designed such that $\\lambda_{N, {\\rm max}} = \\lambda_{N+1, {\\rm min}}$ yield a continuous spectrum when measured in arrival time\n",
```

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "intensity by effectively reducing the time window in which the neutrons can pass.\n",
See comment above. Maybe this is sufficient if it's not easier to derive loss of intensity.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "ds = sc.Dataset(coords=coords)\n",
Until now we haven't used scipp I think. Depending on audience, is it worth linking to other documentation for scipp?

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "We make a data array that contains the beamlineinformation and a histogram of the neutrons over the time dimension."
```suggestion
    "We make a data array that contains the beamline information and a histogram of the neutrons over the time dimension."
```

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "In fact, we can perform a quick check using Scipp's value-based slicing, to verify that the sum of the counts\n",
```suggestion
    "In fact, we can perform a quick check using Scipp's label-based slicing, to verify that the sum of the counts\n",
```

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "    print(\"Lambda:\", lam, \", count in range:\", sc.sum(wav['wavelength', lam - dlam:lam + dlam]).value)"
👍  I think this is readable, but we could alternatively provide the `start`, `end` as variables above.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "By using the information on the `frames`,\n",
This seems a little brief.

Now that we have found the edges for each sub-frame we can apply a correction to shift it from a TOF time based on source t0 to a TOF based on t0n for each sub-pulse. Once our neutrons are adjusted to be in a consistent TOF frame, they can be directly merged between the sub-frames. At this point the WFM procedure is complete and further analysis (expect for filtering maybe) does not need to consider the WFM mode again.

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "We will create a beamline that resembles the ODIN instrument beamline,\n",
```suggestion
    "We will create a beamline that resembles the ODIN instrument beamline, and\n",
```

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "Next, we will generate some fake data that is supposed to mimic a spectrum with a Bragg edge located at $4\\unicode{x212B}$.\n",
```suggestion
    "Next, we will generate some fake imaging data that is supposed to mimic a spectrum with a Bragg edge located at $4\\unicode{x212B}$.\n",
```

2021-08-17 10:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "def has_valid_path(wavelength, birth_time):\n",
Do you still need this?

2021-08-17 11:33 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "where a constant $\\Delta \\lambda / \\lambda$ is much more desirable.\n",
I think it's more that some experiments just need more resolution to properly resolve the features (e.g. Bragg peaks/edges) they are looking at?

2021-08-17 11:34 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "In this context, 'optically blind' indicates that the choppers have the same opening angles,\n",
Yes, they have the same opening angles, also for v20.

2021-08-17 13:06 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "The main reason for using the WFM concept is to redefine the burst time $t_{P} = \\Delta t$ as implied by Eq. (1), in order to match the required wavelength resolution of the experiment."
You are trading off flux, yes. I didn't want to go into too much detail on this because it also depends on the wavelengths of the neutrons, not just the opening times.

2021-08-17 13:07 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "Here we define several important quantities:\n",
I mention the FOC just after, so I think there is no need to repeat it here?

2021-08-17 13:09 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "where a constant $\\Delta \\lambda / \\lambda$ is much more desirable.\n",
True, In the case of the bragg edge, it's just a factor of 2 t switch to d-spacing.

2021-08-17 13:31 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "$t(\\lambda) = \\alpha \\lambda z_{\\rm det}$ to $t(\\lambda) = \\alpha \\lambda (z_{\\rm det} - z_{\\rm WFM})$.\n",
Did you mean `sample`?

2021-08-17 13:42 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "The concept of wavelength frame multiplication implies that no data can be recorded in the\n",
We don't actually expect overlap, apart from the fact that the region Delta_t-wide on the right hand side of frame 1 will overlap with the region Delta_t-wide on the left hand side of frame 2, because by design they are the same wavelength.
This ensures no gaps between the frames.

I think the reason why you would see spikes at the overlap region might be slightly different (non-straight line) flight paths at a real beamline.

2021-08-17 13:44 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "They are designed such that $\\lambda_{N, {\\rm max}} = \\lambda_{N+1, {\\rm min}}$ yield a continuous spectrum\n",
I think makes the point not quite as clear, and would rather leave it out.

2021-08-17 13:45 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "ds = sc.Dataset(coords=coords)\n",
This will be hosted on the scipp.github.io domain, so I think it's fine

2021-08-17 13:46 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "In fact, we can perform a quick check using Scipp's value-based slicing, to verify that the sum of the counts\n",
oh, that's what we call it now?
i somehow missed that. I think i prefered the old name...

2021-08-17 14:27 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "By using the information on the `frames`,\n",
I made it longer, trying to make it more clear.
Please check

2021-08-17 14:28 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "We will create a beamline that resembles the ODIN instrument beamline,\n",
i think there is an `and` just after, so i would say no `and` here?

2021-08-17 14:33 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "Next, we will generate some fake data that is supposed to mimic a spectrum with a Bragg edge located at $4\\unicode{x212B}$.\n",
I addressed this in the other PR, which should be merged first.

2021-08-17 14:34 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "def has_valid_path(wavelength, birth_time):\n",
No, it's been replaced by using a mask. See #42

2021-08-19 12:00 UTC, OwenArnold reviewed
Overall, this is really good. I think this is actually the best description/demonstration of the technique I have found.

2021-08-19 12:00 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "We choose the values for the wavelengths based on the limits given in the `frames` information above."
You could do this programatically, why do this by stating the numbers again?

2021-08-19 12:00 UTC, OwenArnold commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "    print(\"Lambda:\", lam, \", count in range:\", sc.sum(wav['wavelength', lam - dlam:lam + dlam]).value)"
dlam is might better be described as a half width assuming symmetry between + and - values. might want to choose a different name `half_dlam`?

Also there is a repetition of code here between a number of cells above for the stitching and the wavelength resolution tests.

2021-08-19 13:26 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "    print(\"Lambda:\", lam, \", count in range:\", sc.sum(wav['wavelength', lam - dlam:lam + dlam]).value)"
> dlam is might better be described as a half width assuming symmetry between + and - values. might want to choose a different name half_dlam?

ok, i'll do that

> Also there is a repetition of code here between a number of cells above for the stitching and the wavelength resolution tests.

Yes, I think the repetition is meant to illustrate the process I went through when figuring out what was going on. I think it is a small repetition that someone would be doing as part of a natural way of working with the notebook by simply re-executing the cells. So I think it's fine not to write functions for this.

2021-08-19 13:29 UTC, nvaytet commented on docs/techniques/wfm/introduction-to-wfm.ipynb
> +    "We choose the values for the wavelengths based on the limits given in the `frames` information above."
I think because if i programmatically selected the dead center of each frame (which is probably what you would do), then I would go through the openings and I would not see the bad results for frame 1 and 2.

This was meant to illustrate the thought process I went through when writing this notebook, I could not understand why the wavelengths didn't match, until I tried to apply the DLambda/Lambda condition, and thought it was a nice way to understand the way WFM work and what it guarantees.

2021-08-20 07:44 UTC, OwenArnold approved these changes

2021-08-20 08:09 UTC, merged