Event mode wfm
scipp/ess-legacy-v2 pull request #48
Opened 2021-09-10 16:50 UTC by nvaytet

- Add a section in the WFM notebook on how to use the WFM stitching in event mode
- Also add a comparison to a reduction at a beamline without WFM choppers.

2021-09-13 05:11 UTC, SimonHeybrock reviewed
Didn't look at the notebook yet, just the code. Some questions and potential ideas for improvement:

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +            coords_or_attrs)['source_position'] = frames["wfm_chopper_mid_point"].data
Is the reason for removing the source position that `scn.convert` would otherwise use it to compute `L1`?

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +        if item.bins is None:
Isn't this checked by the top-level function?

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
>              out += sc.rebin(section, 'tof', out.meta["tof"])
Is the `rebin` actually necessary to be included here? Could we just copy into the correct slice of `out` (and `rebin` the whole thing later on, if nicely aligned bins are desired)? Or is the issue that there may be different numbers of bins for different pixels? Or do the frames overlap after applying shifts (and that is why the `+=` is needed, rather than an assignment?)?

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
>              "frame", i]
Related to my question about the use of `rebin`: Have you ever considered working with bin centers rather than histograms for the entire stitching procedure, and use `histogram` as the final step? Basically something like:

```python
item.coords['tof'] += time_offset  # also update pulse_time?
stitched = sc.histogram(item, bins=tof_coord)  # assume regions between frames have been offset to be out of range
```

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +        section = piece.events.copy()
Why the copy?

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +        del piece.bins.meta['time']
Can this be done in-place (modifying `time`), such that we avoid the large extra memory allocation for `tof`?

2021-09-13 05:11 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +                out = sc.concatenate(out, section, 'tof')
This is expensive. Can we modify the events in-place instead?

- Instead of extracting individual frames using `bin` (in line 100), do not use a `for` loop, but just use `bin` to cut into frames (but keep everything in the same data array).
- Use in-place coord modification to apply offsets.
- Use (a single) `bin` to map into new `tof` bins and drop events between frames.

2021-09-13 09:08 UTC, nvaytet commented on src/ess/wfm/stitch.py
> +            coords_or_attrs)['source_position'] = frames["wfm_chopper_mid_point"].data
Yes, that is the reason. I guess you are suggesting to just directly set `L1` instead?

2021-09-13 10:04 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +            coords_or_attrs)['source_position'] = frames["wfm_chopper_mid_point"].data
Yes.

2021-09-14 08:40 UTC, OwenArnold requested changes
Overall looks good. Most of my comments are minor.

2021-09-14 08:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "For the events in both `sample` and `vanadium`,\n",
In the view/plot step below. Are we sufficiently sure that users would have encountered the binned data and histogram concepts before? If not you could either:
* point them at the corresponding introductions in `scipp` in the introduction markdown
* briefly introduce the concepts.

2021-09-14 08:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "nevents = 1_000_000\n",
Not directly related to these changes, but you refer to `slopes` in some of the calculations. These are just `velocities` on a time-distance diagram. I think these would be better terms.

2021-09-14 08:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "dt = 0.1 * (tmax - tmin)\n",
What is 0.1 in this context? How did you select it?

2021-09-14 08:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "                         num=257,\n",
We have 257 bins, where did this come from?

2021-09-14 08:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "dt = 0.1 * (tmax - tmin)\n",
Same question as above

2021-09-14 08:40 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "As written above, the `stitch` routine accepts both histogrammed and binned (event) data.\n",
```suggestion
    "As explained above, the `stitch` routine accepts both histogrammed and binned (event) data.\n",
```

2021-09-14 08:40 UTC, OwenArnold commented on src/ess/wfm/stitch.py
> +            _populate_coords(item, out, dim)
keyword args rather than positional would be useful esp given in-place operation.

2021-09-14 08:40 UTC, OwenArnold commented on src/ess/wfm/stitch.py
> +            out[f"frame{i}"] = section
just return here, and then you can avoid subsequent `if merge_frames` condition below.

2021-09-14 08:44 UTC, OwenArnold commented on src/ess/wfm/stitch.py
> +def _stitch_event_data(item: sc.DataArray, dim: str, frames: sc.Dataset,
There seem to be no corresponding unit tests to cover the event stitching cases.

2021-09-14 10:57 UTC, nvaytet commented on src/ess/wfm/stitch.py
> +            coords_or_attrs)['source_position'] = frames["wfm_chopper_mid_point"].data
How would you handle, in a nice way, the cases where you need to set `L1` (because you will use `scatter=True` in the conversion later), and when you need to set `Ltotal` (because you need `scatter=False` for imaging)?
Any good ideas?

2021-09-14 10:57 UTC, nvaytet commented on src/ess/wfm/stitch.py
>              out += sc.rebin(section, 'tof', out.meta["tof"])
yes, rebin is need because there is a small amount of overlap.

2021-09-14 10:59 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "dt = 0.1 * (tmax - tmin)\n",
Just to add a bit of padding. It's already used further up the notebook.

2021-09-14 11:00 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "                         num=257,\n",
The same number as further up the notebook, when WFM choppers are in use. No particular reason for tha number and notebook should work if you modify it.

2021-09-14 11:00 UTC, nvaytet commented on src/ess/wfm/stitch.py
> +def _stitch_event_data(item: sc.DataArray, dim: str, frames: sc.Dataset,
yes, no unit tests for event data yet. Need to add them.

2021-09-14 11:10 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +            coords_or_attrs)['source_position'] = frames["wfm_chopper_mid_point"].data
Not really. I think it might be better to use a special WFM unit conversion graph (instead of adding coords to hit the correct branch inn the standard graph), which would not look for `source_position` but something like `wfm_chopper_position`.

2021-09-14 11:18 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +    # Note: it's better to have frame as the inner dim and pixels as the outer dims
This comment seems unrelated to the line after?

2021-09-14 11:18 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +    del binned.bins.coords[dim]
This would go wrong if `new_dim == dim`, which does not seem to unlikely, I suppose if we just load raw data using, say, `load_nexus` we get `dim='tof'`, which is also what we want as a target dim.

2021-09-14 11:18 UTC, SimonHeybrock commented on src/ess/wfm/stitch.py
> +    return sc.bin(binned, edges=[new_edges], erase=[dim])
Similar to above comment we should consider support `new_dim == dim`?

2021-09-14 13:06 UTC, nvaytet commented on src/ess/wfm/stitch.py
> +            coords_or_attrs)['source_position'] = frames["wfm_chopper_mid_point"].data
Ok, so for now I will just keep the modification of the `source_position` and change it once we have the transform coord graphs in the unit conversion.

2021-09-14 13:13 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "For the events in both `sample` and `vanadium`,\n",
I'm not really sure where to point them to? It could be a large portion of the scipp docs pages.

2021-09-14 13:14 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "nevents = 1_000_000\n",
I had `slopes` because they go along `intercepts`.
I think `velocities` and `intercepts` is a little weird?

2021-09-14 13:32 UTC, nvaytet commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "As written above, the `stitch` routine accepts both histogrammed and binned (event) data.\n",
done

2021-09-15 13:39 UTC, OwenArnold commented on docs/techniques/wfm/reducing-wfm-data.ipynb
> +    "nevents = 1_000_000\n",
I think your intercepts correspond to distances at which the paths would cross. So the term intercept, as in intercept point would still work. Nevertheless this is too minor to worry much about, it can go in as is.

2021-09-15 13:41 UTC, OwenArnold commented on tests/wfm/stitch_test.py
> +@pytest.mark.parametrize("event_mode", [False, True])
👍

2021-09-15 13:43 UTC, SimonHeybrock approved these changes

2021-09-15 14:30 UTC, OwenArnold approved these changes

2021-09-15 14:30 UTC, merged