Diffraction event filtering functions
scipp/ess-legacy-v2 pull request #57
Opened 2021-10-07 09:12 UTC by Pasarus

This is the culmination of work on producing functions that are similar enough to the mantid algorithms that scientists are used to using for Neutron data.

The conversion/functionality is comparable for these:
FilterBadPulses -> filter_bad_pulses
FilterByLogValue -> filter_data_array_on_attribute
FilterByTime -> filter_by_time
FilterByXValue -> (This can be done with normal slicing, bin, groupby etc already)
FilterEvents -> (functions very similar to bin or groupby)
FilterLogByTime -> filter_attribute_by_time
(You could filter the sample log by value easily in mantid, not so easy in scipp so I made a helper function) -> filter_attribute_by_value

2021-10-07 12:52 UTC, jl-wynen reviewed
I have a conceptional question since I don't know how this is supposed to be used. Would it make sense to add a mask that is `True` for bin 0 and `False` for bin 1 to explicitly 'filter' the bad data? Or are users expected to always split the two bins into separate arrays?

2021-10-07 12:52 UTC, jl-wynen commented on tests/diffraction/filter_test.py
> +    _test_filter_sums_for_bad_pulses(filtered_da, 51799.703125, 6282525.0)
Where do those numbers come from?

Maybe it would be better to test smaller data arrays where you can compute the expected results by hand. This would also speed up the tests because we would not load large data files all the time.

2021-10-07 12:52 UTC, jl-wynen commented on src/ess/diffraction/filter.py
> +    Filters out any bad pulses based on an attribute named "proton_charge" if the
Please add and argument to allow users to specify the name of the proton charge attribute. And the same would probably make sense for `"pulse_time"`. They can default to the values used here if those are expected to be used by ESS but we should not force users to use a specific naming scheme.

2021-10-07 12:52 UTC, jl-wynen commented on src/ess/diffraction/filter.py
> +                      centre: bool = False,
Please change to `center`, we use American spelling in scipp.

2021-10-07 12:52 UTC, jl-wynen commented on src/ess/diffraction/filter.py
> +         filtering will occur.
Is there a typo in the 2nd line? I cannot quite understand what you mean. Also, an equation would be nice, regardless of how simple it is.

2021-10-07 12:52 UTC, jl-wynen commented on src/ess/diffraction/filter.py
> +    max_charge *= 1.1  # determine true max (max_value * 1.1)
What does 'true' mean here? I don't understand why you multiply the max by 1.1

2021-10-07 12:52 UTC, jl-wynen commented on src/ess/diffraction/filter.py
> +    good_edges = good_edges.groupby(group='edge').copy(1)
Please use a bool as argument to `copy`.

2021-10-07 13:05 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    Filters out any bad pulses based on an attribute named "proton_charge" if the
These were written with PG3 data in mind, and as defaults, my thoughts was this would be updated as the ESS defaults were determined.

2021-10-07 13:08 UTC, Pasarus commented on tests/diffraction/filter_test.py
> +    _test_filter_sums_for_bad_pulses(filtered_da, 51799.703125, 6282525.0)
this is a case of I didn't comment "magic numbers", truthfully I was unsure what to use for testing this function, the data looks right and inputs will just be adjusted by users as needed to make it "look" right, so besides the fact that's the output and these wills stop regression these numbers mean very little.

2021-10-07 13:09 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +                      centre: bool = False,
Believe it or not auto-correct did this, I will correct, good spot.

2021-10-07 13:11 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    max_charge *= 1.1  # determine true max (max_value * 1.1)
Left over bad comments, thanks for spotting this I will remove them as the code speaks for itself. The max being used is explained the in the function comment.

"if a proton charge is 10% higher
     than the maximum (This won't actually make any difference in comparison to just the
     max value) based on how Mantid did filtering of bad pulses."

2021-10-07 13:12 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    good_edges = good_edges.groupby(group='edge').copy(1)
Can do!

2021-10-07 13:24 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    Filters out any bad pulses based on an attribute named "proton_charge" if the
Added your suggested arguments and an argument for defining the time dimension's name in the attribute.

2021-10-07 13:31 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +         filtering will occur.
Updated and improved, thanks!

2021-10-07 13:33 UTC, Pasarus commented
For FilterBadPulses/filter_bad_pulses the data is either useful or it isn't so my assumption is that users will just want rid of the "bad" data, I then applied this logic to each of the other functions. Hence the use of slicing instead of a mask, it allows you to just have the useful data and dump "bad" data via the gc. In large datasets this will save not small amounts of memory if PG3 data is anything to go by.

2021-10-07 13:46 UTC, jl-wynen commented on src/ess/diffraction/filter.py
> +    max_charge *= 1.1  # determine true max (max_value * 1.1)
Ok, so the reason is 'because Mantid does it'? I am unsure how much we should care about that

2021-10-08 10:46 UTC, SimonHeybrock requested changes

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                             datetime_unit: str = "ns"):
I don't think this is an interface that is in-line with scipp standards. We should only support variables (since units are builtin). I am note sure this entire function is a good idea? I looks like all it provides is a convenience to convert ranges to the correct unit, but in turn requires memorizing a new function name and function signature.

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    return sc.bin(da, edges=[edges])
Why do we need this long and complicated function (mainly the docstring)? Apart from violating the scipp approach of always using quantities (values with unit, i.e., scalar variables) as function parameters, it is also restrictive for now reason. Why do we need a special function just for filtering datetime? Can we not do this filtering explicitly? If there is something inconvenient about have start and end are specified we may consider improving the generic interfaces, or adding a generic helper, but as it is I feel all it does is replicating the unfortunate Mantid situation where we have 1000 different algorithms, of which many do the same thing.

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                      proton_charge_attribute_name: str = "proton_charge",
Just use a data array as input here? Then the user can specify any time-series log, not just those that are stored as attributes.

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                      proton_charge_time_dim_name: str = "time",
Is this required? The proton charge log has to be 1D anyway, so dimension should always be automatic?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    max_charge *= 1.1
Hard coded?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    good_pulse = (proton_charge >= min_charge) & (proton_charge < max_charge)
We should probably make everything until here available as a separate function?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                              min_value: sc.Variable, max_value: sc.Variable):
Why is this used for in practice?

Shouldn't this be made more generic to simply do this for a data array, rather than the value of an attribute of a data array? That is, is there any need for the restriction and the ensuring complicated function signature?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    filter_coord_name = _generate_random_string()
You are hoping to avoid name clashes like this? Have you considered using something like `'_'.join(da.coords)`?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    attribute.coords[filter_coord_name] = in_range.data
I don't think we should add attributes to an existing data array. Make a shallow copy beforing doing this? (`da.copy(deep=False)`)

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +def filter_data_array_on_attribute(da: sc.DataArray,
I don't think the `data_array` in the function names adds anything?

This function does not actually seem to filter by an attribute, rather it filters/extract intervals?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    good_edges = good_edges.groupby(group='edge').copy(True)
Move edge finding to separate function?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    da.bins.coords[data_slices_name] = good_pulse_lut[da.bins.coords[mapping_coord]]
Adding coord to input... maybe not ideal?

2021-10-08 10:46 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    good_data_coord = good_data_lut.coords[mapping_coord]
Is there a reason for supporting anything other than the dimension-coordinate, i.e., the one where the name matches the dim?

2021-10-11 08:16 UTC, nvaytet requested changes

2021-10-11 08:16 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +    Args:
You may have copied the docstring style from the reflectometry code that is already in the `ess` repo, but I have actually asked Drew to change this to the Sphinx docstring format (https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format), so that it's the same as in `scipp` and `scippneutron`.
The google style that you are using causes issues with the formatting/indentation of long lines in sphinx.

Sorry, we should really write this in our style guidelines.

2021-10-11 08:33 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    Args:
I just used the default that pycharm gave me here, I will update it before final version.

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +                      proton_charge_time_dim_name: str = "time",
I have made this automatic

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +                      proton_charge_attribute_name: str = "proton_charge",
We can do this yeah.

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    max_charge *= 1.1
Now an optional threshold passed into the function.

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    good_pulse = (proton_charge >= min_charge) & (proton_charge < max_charge)
I'm not sure it makes sense to do this, would you look at this again (as I can appreciate it's been 2 weeks since you said this) and let me know why we should do this?

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    return sc.bin(da, edges=[edges])
The main thing this function does is provide filtering for date inputs before putting them through the normal filtering, if you think I should remove it, I can do so. The aim is to simplify the use of Scipp and writing of workflows with dates in whatever format they are present, and provide the functionality available in Mantid.

Perhaps we should have a discussion as to what we are aiming to achieve with these functions long term? Perhaps with Celine?

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    good_data_coord = good_data_lut.coords[mapping_coord]
In some data produced at the SNS it uses both `time` and `pulse_time` interchangeably for attributes and the event dimensions/coordinates, hence all of this mapping, as I am not sure we know how the ESS intends to do this long term? I suppose we don't want to support hard coding of dim/coord names.

So we should just ensure/rely on whatever is passed in the good_data_lut has the correct dim-coordinate names?

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    da.bins.coords[data_slices_name] = good_pulse_lut[da.bins.coords[mapping_coord]]
Not ideal, would you suggest something like a shallow copy instead?

2021-10-22 10:52 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    good_edges = good_edges.groupby(group='edge').copy(True)
I can, however, it would at present only be used in this function and thus private so I am not sure it would be worth it. It will look like this:
```
def _find_edges_based_on_lut(da: sc.DataArray, good_data_lut, mapping_coord):
    good_data_coord = good_data_lut.coords[mapping_coord]
    edge = good_data_lut.data
    edge = edge[mapping_coord, :-1] ^ edge[mapping_coord, 1:]
    good_edges = sc.Dataset(data={
        mapping_coord: good_data_coord[mapping_coord, 1:],
        'good': good_data_lut.data[mapping_coord, :-1]
    },
                            coords={'edge': edge})
    return good_edges.groupby(group='edge').copy(True)
    

def filter_on_attribute(da: sc.DataArray,
                        good_data_lut,
                        mapping_coord: str,
                        data_slices_name: str = "slice_data"):
    edges = _find_edges_based_on_lut(da, good_data_lut, data_time_coord)
    good_data = sc.DataArray(data=good_edges['good'].data
                             ^ good_data_lut[mapping_coord, 0].data,
                             coords={mapping_coord: good_edges[mapping_coord].data})
    good_data = sc.concatenate(good_data_lut[mapping_coord, 0], good_data,
                               mapping_coord)
    good_data = sc.concatenate(good_data, good_data_lut[mapping_coord, -1],
                               mapping_coord)
    good_pulse_lut = sc.lookup(good_data, mapping_coord)

    da.bins.coords[data_slices_name] = good_pulse_lut[da.bins.coords[mapping_coord]]
    groups = sc.array(dims=[data_slices_name], values=[False, True])
    grouped = sc.bin(da, groups=[groups])
    return grouped
```

2021-10-22 11:10 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    good_data_coord = good_data_lut.coords[mapping_coord]
> So we should just ensure/rely on whatever is passed in the good_data_lut has the correct dim-coordinate names?

Yes. We have to avoid adding hacks for bad input values (this is imo one of the big problems of Mantid). This seriously complicates unit testing and documentation. It is hard to understand and not sustainable.

2021-10-22 11:44 UTC, arm61 commented on src/ess/diffraction/filter.py
> +    Args:
I knew I hadn't pulled this style out of nowhere!

2021-10-26 07:26 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    Args:
They should be up to standard now!

2021-10-26 08:55 UTC, SimonHeybrock reviewed
Some thoughts below, with some of the initial things cleaned up, maybe we can now see a bit better through the forest, which might eventually let us come up with a generic and simple API? Maybe be worth discussing in a call.

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                              data_slices_name: str = "slice_data"):
This function name and the param names feel odd?
- The function does not "filter", but bin/split
- No attribute is involved.
- It is not splitting by edges, but based on data values, and actually only supports two specific valiues (true and false).
- `good_data_lut` does not make much sense?

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    da.bins.coords[data_slices_name] = _find_da_coords_for_slicing(da, good_data_lut)
Should this be deleted after the operation?

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    return data_in_range
```suggestion
    filter_coord_name = '_'.join(da.coords)
    da.coords[filter_coord_name] = da.data
    data_in_range = da.groupby(filter_coord_name, bins=sc.concat([min_value, max_value], filter_coord_name)).copy(0)
    del data_in_range.coords[filter_coord_name]
    del da.coords[filter_coord_name]

    return data_in_range
```

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    return grouped
Given the difficulty of finding a good function name, maybe this should not exist at all (for now)? It is always hard to remove things once they were added (unless we make it really clear that it is experimental).

Maybe we can think about the underlying things we want to do (not saying this has to be done here and now, just thinking out loud):

1. We have a (time-)series-log, defining a value for each (time-)interval.
2. We are optimizing the log to merge intervals with identical values. Since this is simply to avoid performance issues when mapping the events into intervals we would probably want to avoid exposing this to the user.
3. Create new coord that will be used for binning.
4. Create grouping coord based on all unique values of the log.
5. Apply `sc.bin`

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                                                proton_charge.data.values[:-1])
To be honest I still don't really understand this bit.

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    max_charge *= maximum_threshold
With this definition and `maximum_threshold > 1.0` below we will *always* fulfill `proton_charge < max_charge`?

2021-10-26 08:55 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    good_pulse = (proton_charge >= min_charge) & (proton_charge < max_charge)
Instead of having a special function that does two things but only works for pulse-time filtering, would it make sense to have:

```python
# better name may be needed
# `select_band` could also to the joining of adjacent intervals
good = select_band(proton_charge, 0.95, 1.1).rename_dims({'time', 'pulse_time'})
da.bins.coords['good'] = sc.lookup(good)[da.bins.coords['pulse_time']]
sc.bin(da, groups=[sc.unique(good.data)])  # sc.unique is not implemented yet
```

2021-11-03 06:09 UTC, SimonHeybrock reviewed
Some more comments below. I think we are getting closer to having found a more generic mechanism, but I suspect the API will need more iterations (later).

@nvaytet how should we proceed with this? We may want to avoid having too many people rely on this, given that we will change the API later on. Would it make sense to have an `experimental` submodule? Other ideas?

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +     filter(da, ((temp >= min_temp) & (temp < max_temp)), "dim") where temp is the a
```suggestion
     filter(da, ((temp >= min_temp) & (temp < max_temp)), "temperature") where temp is the a
```

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +     event time coordinate should have true or false as the corresponding data of the
Since we have generalized this it can be any event parameter, not just time?

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +     or 1 (True).
Is this due to the current limitation of `_find_edges`?

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    :return: The original da, with  slices of given dim, sliced based on the event bands
It is returning a new data array, not the original.

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    da.bins.coords[dim] = sc.lookup(edges, coord_name)[da.bins.coords[coord_name]]
Should this be removed after the operation?

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +        proton_charge.coords.pop(proton_charge_time_dim_initial_name)
```suggestion
    proton_charge = proton_charge.transform_coords(data_time_coord,
        {data_time_coord: proton_charge.dims[0]},
        keep_inputs=False)
```

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                      maximum_threshold: float = 1.0,
With this default, the interval that saw the maximum proton charge will be dropped, given how the condition is implemented below.

2021-11-03 06:09 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    return filter(da=da, condition_intervals=good_pulse, dim="pulse_slices")
Why did you chose `pulse_slices`, which does not say much? How about `'good_pulse'` or something like that?

2021-11-03 08:27 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    return filter(da=da, condition_intervals=good_pulse, dim="pulse_slices")
So at the moment it is returning both good and bad pulses, hence `pulse_slices`

2021-11-03 08:28 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +                      maximum_threshold: float = 1.0,
Then I'll increase it back to 1.1

2021-11-03 08:30 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +        proton_charge.coords.pop(proton_charge_time_dim_initial_name)
Implemented

2021-11-03 08:31 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    :return: The original da, with  slices of given dim, sliced based on the event bands
Updated

2021-11-03 08:31 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +     or 1 (True).
Yes

2021-11-03 08:32 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +     event time coordinate should have true or false as the corresponding data of the
Yes/no I am not sure where this would be useful, besides using it on event time?

2021-11-03 08:32 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +     filter(da, ((temp >= min_temp) & (temp < max_temp)), "dim") where temp is the a
Done

2021-11-03 08:33 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    return filter(da=da, condition_intervals=good_pulse, dim="pulse_slices")
You have a coord that says "False" and "True". So you would:
```python
da['pulse_slices', sc.scalar(True)]
```
to select the good data. That is meaningless?

If you name the coord `good_pulse` you have:
```python
da['good_pulse', sc.scalar(True)]
```
which clearly expresses intent.

2021-11-03 08:33 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +                      maximum_threshold: float = 1.0,
Or change the math to include the upper bound.

2021-11-03 08:45 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    return filter(da=da, condition_intervals=good_pulse, dim="pulse_slices")
Ok I'll change it to good_pulse

2021-11-03 09:22 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    da.bins.coords[dim] = sc.lookup(edges, coord_name)[da.bins.coords[coord_name]]
Yes, added the removal.

2021-11-03 14:18 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +def filter_bad_pulses(da: sc.DataArray,
Is this name from Mantid? Looking at the other functions below, I would have thought something like `filter_by_proton_charge` would be a better name?
It is subjective what one calls a "bad" pulse. The criterion may not always be proton charge?

2021-11-03 14:18 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +    :param da: sc.DataArray, the data array that is to be filtered.
I believe the type hints should provide the information on the input type to sphinx, so I don't think you need to repeat them in the docstring. I think all you need is the whether it is optional, and the default value if applicable.

2021-11-03 14:18 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +    :return: sc.DataArray or sc.Variable, whichever the attribute is in the original da
I don't really understand in what case it could be a Variable, since `data_in_range` appears to always have coords below?
> `del data_in_range.coords[filter_coord_name]`

2021-11-03 14:18 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +def _find_edges(condition_intervals):
Could you add type hints and docstring here also? Thanks!

2021-11-03 14:18 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +    mapping_coord = condition_intervals.dims[0]
```suggestion
    mapping_dim = condition_intervals.dims[0]
```

2021-11-03 14:18 UTC, nvaytet commented on tests/diffraction/filter_test.py
> +    np.testing.assert_almost_equal(good_da_sum, good_sum)
we prefer to use plain `assert` instead of `np.testing.assert_almost_equal`,
e.g. `assert sc.identical(good_da_sum, bad_da_sum)` or use `sc.allclose()`

2021-11-03 14:18 UTC, nvaytet commented on tests/diffraction/filter_test.py
> +    da = scn.data.tutorial_event_data()
Should we use generated data we have more control over, instead of actual data? so that we don't end up with magic numbers below.

2021-11-04 07:31 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    del da.coords[filter_coord_name]
When the `bins` argument is used, `groupby` accepts a variable as the first argument, so we can avoid the temporary insertion of a new coord:
```suggestion
    data_in_range = da.groupby(da.data,
                               bins=sc.concatenate(min_value, max_value,
                                                   filter_coord_name)).copy(0)
    del data_in_range.coords[filter_coord_name]
```

2021-11-04 09:47 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    del da.coords[filter_coord_name]
Even with this change, it had the coord there, perhaps clean up isn't properly handled by groupby?

2021-11-04 09:49 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    del da.coords[filter_coord_name]
I don't think `groupby` is adding coords to the input, can you double check?

2021-11-04 10:35 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    da.bins.coords[dim] = sc.lookup(edges, coord_name)[da.bins.coords[coord_name]]
@nvaytet @Pasarus I occurs to me that it may make sense to do this "find edges" optimization within `sc.lookup`? The result should be unchanged, and it is essentially just for internal speedup. What do you think?

2021-11-04 10:45 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    del da.coords[filter_coord_name]
I just looked at it and it seems it was removing a coordinate that shouldn't be removed. So you are correct.

2021-11-04 14:18 UTC, Pasarus commented on tests/diffraction/filter_test.py
> +    np.testing.assert_almost_equal(good_da_sum, good_sum)
Whilst I agree plain assert would be better, assert almost equal is necessary due to float addition and rounding errors.

2021-11-04 14:18 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    mapping_coord = condition_intervals.dims[0]
:+1:

2021-11-04 14:18 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +def _find_edges(condition_intervals):
This is a private function, not meant for users to use, hence no docs.

2021-11-04 14:18 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    :return: sc.DataArray or sc.Variable, whichever the attribute is in the original da
I think this was a left over from a previous interpretation of filter by value, good spot!

2021-11-04 14:18 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    :param da: sc.DataArray, the data array that is to be filtered.
I'll remove the types from the doc strings. I will add the Optional and defaults for those that are.

2021-11-04 14:18 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +def filter_bad_pulses(da: sc.DataArray,
I think it is a better name I shall change it.

2021-11-05 09:27 UTC, nvaytet commented on src/ess/diffraction/filter.py
> +def _find_edges(condition_intervals):
Yes, but it still helps the code review process, you could add just a normal comment instead of a proper docstring if you prefer?
Not a big deal, but I would have spent less time understanding what the code was trying to achieve with a comment at the top.

2021-11-05 09:28 UTC, nvaytet commented on tests/diffraction/filter_test.py
> +    np.testing.assert_almost_equal(good_da_sum, good_sum)
Yes, and you can use `sc.allclose` for that? and then you don't need to get the `.value`

2021-11-05 09:30 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +def _find_edges(condition_intervals):
This can actually be removed entirely, due to https://github.com/scipp/scipp/pull/2264. This should also remove the restriction to boolean inputs.

2021-11-05 09:31 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +def _find_edges(condition_intervals):
Should I remove this function, then and wait for scipp to release a new version?

2021-11-05 13:02 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
Should we consider support `str` in the list of `groups`, such that groups will be automatically determined? That is what `groupby` does, so it would be consistent. That is, we could then write:

```python
grouped = sc.bin(da, groups=[dim])
```
instead of the 3 lines above.

2021-11-05 13:03 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
Maybe not, because it could be quite inefficient in practice?

2021-11-05 13:14 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
I am struggling to think of the benefit of supporting `str` in the list of groups? Would this be so we don't need to support `datetime64`? or would it be so we can use a dimension in the `da` opposed to pulling it out and then putting it back into `sc.bin?`

2021-11-05 13:18 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
The benefit would be to spare two lines of code to determine the possible groups, instead doing it automatically.

2021-11-05 13:21 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
Yeah I see that now, would this be clear to users of scipp? Like do we do this in other places? and should we add them if not?

2021-11-05 13:23 UTC, SimonHeybrock commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
> Like do we do this in other places?

We do (see above): https://scipp.github.io/user-guide/groupby.html

2021-11-05 13:33 UTC, Pasarus commented on src/ess/diffraction/filter.py
> +    grouped = sc.bin(da, groups=[groups])
So it makes sense to support this in Scipp itself yes.

2022-10-14 03:39 UTC, SimonHeybrock commented
I had a final brief look at this. With the recent enhancements in Scipp (either already available, or with the next release) I think this is fully obsolete. This includes the units test. I'll there close this, unless there are objections.

2022-10-14 03:39 UTC, closed without merging