Changes for imaging notebooks
scipp/ess-legacy-v2 pull request #6
Opened 2021-02-03 14:28 UTC by nvaytet

- Add v20 beamline chopper parameters
- Add wfm module for analytical frame calculation and tof stitching
- Add peak finding frame calculation from `dress` repository but this has not been tested yet.
- Add groupby2d function used in bragg edge imaging notebook.

2021-02-04 12:20 UTC, OwenArnold requested changes
Good work thus far - we are very much lacking testing and documentation, but maybe we should immediately work on that together after this has been merged rather than trying to do that all here and otherwise holding the notebook publication up?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +    return (2.0 * np.pi * sc.units.rad) * (f / (1.0 * sc.units.s))
if `f` is Hz, should be 1/s already?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +    Create V20 chopper cascade and component positions.
beamline method only contains choppers, no other component positions? I see in the notebooks you append additional components to it based on the experiment (a good idea). Should this maybe just be renamed to imply that you are not going to get the full beamline?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +    ds["pulse_length"] = 2.86e+03 * sc.units.us
Isn't this also chopper derived? Or maybe not worth performing, in which case we can comment on why

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +    ds["distance"] = sc.array(dims=["chopper"],
Chopper cutout information is pretty well baked into the beamline, but frequency is an experiment level configuration (should be injected). I believe the WFM choppers are on motors so they can be brought together (or moved further apart) to change the wavelength resolution, so those should be parametrised too. TDC should be fixed for the choppers, but as we've seen TDC is not always correctly known, so maybe that should be parameterised too.

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +                              values=[[0, 0, 6.6], [0, 0, 7.1], [0, 0, 8.8],
Not defined what 0, represents - this is not for example a nexus instrument frame, so maybe should define what the origin is. Also assumed that users will know that z is the beam direction. Could we maybe set an attribute (scalar vector_3) to define?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
I think astype will elide the conversion if target and original are the same?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/imaging/operations.py
> +        for c in ["wavelength", "source-position"]:
Wouldn't this be more general if we were using any coord not in `x`, `y`. And maybe those two coords could be input args?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/wfm/__init__.py
> +from .stitch import stitch
I'm not 100% on having things in the ess package that are outside the `facitlity/instrument/experiment-type` structure. I feel this would quickly decay into all kinds of `misc`, `utility`, `tools` package at every level. While it seems like a regression - I suggest putting all the WFM code alongside v20. The advantages of this I see are:

* We are not overpromising on it's general functionality. If another instrument area attempts to use it, it's clearler that we have only tested this for working with V20. Moderator neutron velocities (constraining) might be critical to avoid frame overlaps for other instruments but we don't need to introduce them for v20. Maybe lots of other assumptions.
* In the former case, it's a trigger to promte it to the `scipp-neturon` package.

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +    source to pixel. We should use l1 + l2 in the future.
Depends on the technique. For imaging we should not do l1 + l2.

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +                                unit=sc.units.us)
This function has two roles (1) compute frame boundaries and shifts (2) plot the results. Can we better seperate the two concerns in the code. I think that having the `plot` flag is not a bad thing, but maybe we should call one sub function to perform the calculations and have a second function to do the plotting (based on the results) provided `plot=True`

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +def frames_analytical(instrument=None, plot=False, offset=None):
Why default initialise instrument rather than making it a required parameter?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/wfm/frames_peakfinding.py
> +  Find WFM frames using peak-finding.
For people not familiar with the idea - maybe explain the premise that frames should not overlap in time and we can therefore identify minima using fitting to find the centres of the gaps?

2021-02-04 12:20 UTC, OwenArnold commented on src/ess/v20/imaging/operations.py
> +    edges_mask = sc.less_equal(container,
minor point: `<=` rather than named function now we support it?

Not sure why this didn't also require an update to the operations tests.

2021-02-08 09:45 UTC, nvaytet commented on src/ess/v20/beamline.py
> +    ds["pulse_length"] = 2.86e+03 * sc.units.us
I would say it's not worth deriving this from choppers, as they are meant to simulate the ESS pulse anyway. I'll add a note as a comment.

2021-02-08 10:22 UTC, nvaytet commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
i think `astype` always does the conversion.

2021-02-08 10:23 UTC, nvaytet commented on src/ess/v20/imaging/operations.py
> +        for c in ["wavelength", "source-position"]:
There were hard-coded dimension label everywhere in that file so i left it as is.

2021-02-08 10:37 UTC, OwenArnold commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
It has to return a `Variable`, so a copy is made even if dtype is the same.

2021-02-08 11:02 UTC, nvaytet commented on src/ess/wfm/frames_analytical.py
> +                                unit=sc.units.us)
I would say it's not really 2 completely separate things. The plotting is just showing you in a graphical way what was done to compute the frames, a bit like a sanity check.
I can move all the plotting stuff into a separate function but I then have to pass many quantities as arguments, or repeat several calculations to find, e.g. the lengths of the chopper openings in microseconds.
I could move these small calculations to separate functions i guess...

2021-02-08 11:05 UTC, OwenArnold commented on src/ess/wfm/frames_analytical.py
> +                                unit=sc.units.us)
Yes, separate functions for the calculations sounds good. I think refactoring this is worthwhile given its importance. At present, there are multiple checks for the plotting flag.

2021-02-08 11:11 UTC, nvaytet commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
Yes, a copy is always made. This is the same as the original code.
I'm not sure I understand the issue here

2021-02-08 11:27 UTC, OwenArnold commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
my point is whether this is performing unnecessary work in that the dtype does not need to change. It looks like it is and can be avoided. Agree that this was the same in the original code, but fix should be simple.

2021-02-08 11:34 UTC, nvaytet commented on src/ess/wfm/frames_peakfinding.py
> +  Find WFM frames using peak-finding.
This part of the code has not been tested for at least 6+ months, I've just included here so that all code is in the same place. I don't really want to spend time documenting something that will change again.
I think it's beyond the scope of this PR.
Maybe I can just disable the peak-finding branch for now, to prevent anyone from trying to use it?

2021-02-08 11:39 UTC, nvaytet commented
> we are very much lacking testing and documentation

I totally agree about tests and docs. I'll open an issue.

2021-02-08 11:41 UTC, nvaytet commented on src/ess/v20/beamline.py
> +    ds["distance"] = sc.array(dims=["chopper"],
Added possibility to pass chopper parameters (frequency, phase, etc..) as a dict to the chopper cascade constructor.

2021-02-08 11:42 UTC, nvaytet commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
Or maybe this should be a fix that could be implemented in scipp directly, so that we don't have to have `if` statements in all our notebooks?

2021-02-08 12:25 UTC, nvaytet commented on src/ess/v20/beamline.py
> +                              values=[[0, 0, 6.6], [0, 0, 7.1], [0, 0, 8.8],
Not sure what you mean here exactly. You mean set an attribute that would contain the origin?
Since this is just for `v20` i don't every see the positions of the choppers moving, so I don't think it's that important. I added a comment saying that the convention was assuming that [0, 0, 0] is the source chopper.

2021-02-08 12:42 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +                              values=[[0, 0, 6.6], [0, 0, 7.1], [0, 0, 8.8],
Yes, that's what I meant, that the something called origin would return the source chopper. Documenting that aspect is fine.

Regarding the beam direction, we have the beam running parallel to z `[0, 0, 1]` my idea was to encode that to make downstream calculations easier (dot product etc).

2021-02-08 12:42 UTC, OwenArnold commented on src/ess/v20/beamline.py
> +                              values=[[0, 0, 6.6], [0, 0, 7.1], [0, 0, 8.8],
I'm ok with both being documented for the time being.

2021-02-09 09:41 UTC, OwenArnold commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
Without the function returning a view, i'm not sure we can put the fix on the scipp side.

2021-02-09 09:42 UTC, OwenArnold commented on src/ess/v20/imaging/operations.py
> +        for c in ["wavelength", "source-position"]:
It would be nice to fix this, and move the dimension info to the args - but maybe it can wait for some follow up.

2021-02-09 10:28 UTC, nvaytet commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
Not sure how you want to implement a quick fix here because
```Py
np.float64 == sc.dtype.float64
```
returns `False`. So I don't really know how to check that the types differ because
```Py
if dtype != stack.dtype:
    stack = stack.astype(dtype)
```
won't work.

2021-02-09 10:39 UTC, OwenArnold commented on src/ess/v20/imaging/helper_funcs.py
> +    data = stack.astype(dtype)
What i've had to do in the past is something like.
`np.Variable(value=1, dtype=np.float64).dtype == sc.dtype.float64` but clearly that's not nice. Just leave it as it is for now.

2021-02-09 11:17 UTC, OwenArnold commented on conda/meta.yaml
> +    - src/ess/
```suggestion
    - tests/
```

2021-02-09 11:18 UTC, OwenArnold commented on conda/meta.yaml
> +    - src/ess/
Without this pytest won't run anything and the `conda build` step will fail.

2021-02-09 13:15 UTC, OwenArnold approved these changes

2021-02-09 13:20 UTC, merged