First pass for logging
scipp/ess-legacy-v2 pull request #93
Opened 2022-01-27 15:17 UTC by jl-wynen

Implements logging for reflectometry and Amor.
This will probably need many iterations to figure out what, how, and where to log. But the high level API (`get_logger`, `configure[_workflow]`) should be kind of final when the PR is merged so that we can start using it across techniques. Please take that into account when reviewing.

The  TODO about Mantid can only be resolved when Mantid 6.4 is released which provides an API to forward its logs to Python.

2022-01-28 10:29 UTC, nvaytet requested changes

2022-01-28 10:29 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger = ess.logging.configure_workflow('amor_reduction',\n",
It feels a bit strange that one has to manually do this in a notebook. Ideally, users should not have to care about setting up logging, they would probably expect this to happen automatically behind the scenes.
But I am not sure if it is possible to do in another way.

You are doing it this way because you want to log the name of the notebook, but is that really necessary? I guess users know which notebook they are running, and I am not sure how often one would be running multiple notebooks to do a reduction.

Would it be possible instead to initialize this when the `amor` module is imported? So that we can configure the logger to at least have `amor`?

I guess this would mean that when you import `ess`, you spawn the loggers for all the submodules (`amor`, `loki`, `wfm` etc.). Would that be an issue? Can you even have multiple loggers?
You could then do `amor.logger(...)`

2022-01-28 10:29 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "tags": []
Why the empty `tags`?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/amor/beamline.py
> +import logging
Is this the python `logging`, and below we have the local `ess` logging?
This feels quite error prone.

2022-01-28 10:29 UTC, nvaytet commented on src/ess/amor/beamline.py
> +@log_call(message='Constructing artificial AMOR beamline parameters')
```suggestion
@log_call(message='Constructing AMOR beamline parameters')
```

2022-01-28 10:29 UTC, nvaytet commented on src/ess/amor/load.py
> +from typing import Optional
Not sure I understand what using `Optional` brings, generally.
If the argument has a default value, it is optional. You don't really need to speel it out even more?
Sphinx's autodoc will even add the `Optional` tags for you automatically.
But maybe that is a wider discussion we can have somwhere else?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/amor/load.py
> +         beamline: Optional[dict] = None,
Why is `beamline` `Optional`, but not `disable_warnings` below?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/amor/load.py
> +    beamline = make_beamline() if beamline is None else beamline
This is a better way to do things than creating the beamline in the default args, because it used to get created as soon as you import `ess`, even if you are never going to call it. :+1: 

There are probably other places in the reflectometry where we were doing the same, and should use `None` instead?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/logging.py
> +    # Assumes package name: ess.<instrument>[.subpackage]
This sounds like it's going to break at some point (e.g. if we decide to move the instruments into an `instruments` folder).
Do we really need this? Can we require the instrument name to always be specified?

The module inspection to find the name also sounds expensive, if you make 1,000,000 calls to a function that is logging?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/logging.py
> +        The general as well as date formats are fixed.
Not sure I understand the meaning of the sentence. What is `general` here?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/logging.py
> +    *Calling it from a library should be avoided because*
So when can it be called? When you are in a notebook?

2022-01-28 10:29 UTC, nvaytet commented on src/ess/logging.py
> +                     Settings this to `None` disables logging to file.
```suggestion
                     Setting this to `None` disables logging to file.
```

2022-01-28 10:29 UTC, nvaytet commented on src/ess/logging.py
> +    :param stream_level: Log level for the stream handler.
You should also list the default values at the end of the `:param` entries.
You would think that sphinx could do that for you automatically, but I tried to use a package to do that once and it messed things up, and I couldn't build the docs anymore :-1:

2022-01-28 11:02 UTC, jl-wynen commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger = ess.logging.configure_workflow('amor_reduction',\n",
> You are doing it this way because you want to log the name of the notebook, but is that really necessary?

The notebook name is not logged. The name passed in here is only used as the name of the returned logger. This is not really necessary, users can create loggers themselves.

Concerning the main point, there are 2 distinct issues here.

Configuring at import is generally a bad idea as that slows down import. In particular logging the program version would be bad because that creates a new file or overwrites an existing one which one would not expect to happen during import. Also, this would mean that logging can never be customised programmatically, one would need a config file.
Configuration could be deferred until someone first calls `get_logger` to solve this issue.

But this links to the 2nd issue. ess is still primarily a library. As such, configuring logging automatically forces that configuration onto every user. Imagine someone at SNS importing the WFM module. That user would be forced to use our logging setup. Or, if they are aware of it, wipe the setup before doing theirs.

One possible solution would be an IPython magic. At the UX workshop we talked about the boilerplate import code that kind of distracts from the actual meaning of the notebook. We could implement a magic that imports all default modules and configures logging. Not sure this is actually a good solution because it hides the definition of names (like `import scipp as sc`), but I wanted to throw it out there...

There is also a way of automatically executing some code whenever Python starts. We could configure this on ESS machines to do whatever setup we need. But that would then be inconsistent with user's own machines. Or we do it for every env that ess is installed in. Which would again force the setup on everyone using the package.

> Can you even have multiple loggers?

As many as you like.

> I guess this would mean that when you import ess, you spawn the loggers for all the submodules (amor, loki, wfm etc.). Would that be an issue

Constructing a logger does not perform any setup. Creating instances for all submodules would not do any harm. But it would mean that we cannot tie setup to `get_logger` if that is the route we want to take.

2022-01-28 11:05 UTC, jl-wynen commented on docs/instruments/amor/amor_reduction.ipynb
> +    "tags": []
Don't know how they got there. Going to remove them.

2022-01-28 11:07 UTC, jl-wynen commented on src/ess/amor/beamline.py
> +import logging
Would you prefer renaming our module?
In this particular case, we don't need to import the std lib logging because we can use strings: `@log_call(level='DEBUG')`. And we probably never need to do so outside of our logging module.

2022-01-28 12:21 UTC, jl-wynen commented on src/ess/amor/load.py
> +from typing import Optional
It's not about sphinx but about type checkers. I don't know if they add Optional automatically.

2022-01-28 12:22 UTC, jl-wynen commented on src/ess/amor/load.py
> +         beamline: Optional[dict] = None,
Didn't pay attention to it

2022-01-28 12:26 UTC, jl-wynen commented on src/ess/logging.py
> +    # Assumes package name: ess.<instrument>[.subpackage]
> Do we really need this? Can we require the instrument name to always be specified?

You could also argue that when a function is moved to a different module, the user might have to update the name. With the automatic detection, it would just work.
But I agree with you and I was unsure whether I should implement this. Shall I remove it?

> The module inspection to find the name also sounds expensive, if you make 1,000,000 calls to a function that is logging?

The decorator is only evaluated when the function is defined. After that, the name is stored. So the cost does not really matter.

2022-01-28 12:27 UTC, jl-wynen commented on src/ess/logging.py
> +        The general as well as date formats are fixed.
`logging.Formatter` takes two formats, one for the message and one for the date. I'll clarify.

2022-01-28 12:27 UTC, jl-wynen commented on src/ess/logging.py
> +    *Calling it from a library should be avoided because*
Or when you write an app of any sort.

2022-01-28 12:28 UTC, jl-wynen commented on src/ess/logging.py
> +    :param stream_level: Log level for the stream handler.
It does list them. But not in the params items, only in the signature at the top.

2022-01-28 13:18 UTC, jl-wynen commented on src/ess/amor/load.py
> +    beamline = make_beamline() if beamline is None else beamline
The `make_beamline` function itself takes a bunch of scipp variables as default values. This is generally bad because mutable defaults should be avoided. But avoiding that would be a lot of faff. Should I do it or is it fine the way it is in this particular case?

2022-01-28 13:20 UTC, jl-wynen commented on src/ess/amor/beamline.py
> +@log_call(message='Constructing artificial AMOR beamline parameters')
I put the log there because I thought that this function would eventually be replaced by loading that data from file. If this is expected to be the default way of getting beamline parameters, we may want to remove `log_call`.

2022-01-28 14:32 UTC, nvaytet commented on src/ess/amor/load.py
> +    beamline = make_beamline() if beamline is None else beamline
I think we can defer to another PR, it's not really related to logging.

2022-01-31 09:44 UTC, nvaytet commented on src/ess/amor/beamline.py
> +@log_call(message='Constructing artificial AMOR beamline parameters')
You are right that it is not the way it will be done in the future. It will be read from the Nexus files, so logging something is good).
However, I thought saying 'artificial' was a little strange, since Amor is an existing beamline with known parameters. Maybe we should have a different message. Something like
```
The beamline parameters were not found in the Nexus file. Constructing a beamline from default values.
```
?

2022-01-31 09:45 UTC, nvaytet commented on src/ess/amor/load.py
> +         beamline: Optional[dict] = None,
I guess if we change those, we should add `Optional` to all the functions in the `amor` and `reflectometry` modules.
But should be a different PR.

2022-01-31 09:46 UTC, nvaytet commented on src/ess/logging.py
> +    # Assumes package name: ess.<instrument>[.subpackage]
> Shall I remove it?
I would say simple is always better, so until someone complains about having to type the instrument name, we can remove?

2022-01-31 09:49 UTC, nvaytet commented on src/ess/logging.py
> +    :param stream_level: Log level for the stream handler.
True. I always thought we should do like the Numpy docs, who lists them both in the signature and in the `:param:` block. But on second though, it is duplicating info, and it is less likely to get out of sync by just having them in the signature.
Maybe I should have a look at all the docstrings and change accordingly?

2022-01-31 09:57 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
What about having the `load` function do the logging instead?
You pass it the `logger` as an argument, and inside `load`, `if logger is not None`, log a message?
Same for the other functions below?

2022-01-31 09:57 UTC, nvaytet commented on src/ess/logging.py
> +                       display: bool = running_in_jupyter(),
I'm wondering if, as you did for the beamline, we shoudl avoid calling functions for default parameters?
Set to `None` and make the jupyter check when function is called?

2022-01-31 10:24 UTC, jl-wynen commented on src/ess/logging.py
> +                       display: bool = running_in_jupyter(),
I don't think there is a problem with calling functions as such. It slows down the creation of the function object a little. But since the result in this case is a (immutable) bool, there is no real harm.
I did it like this so that `running_in_jupyter` shows up in the docs. But it is actually just resolved by sphinx and replaced by `False`, which is not very informative. So I am going to change it.

2022-01-31 10:26 UTC, jl-wynen commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
`load` does not know what kind of file it is loading. It makes sense to log every file that is loaded, so I am going to add that to the `load` function. But it would also be nice to show some info, like `loading normalisation`, etc. Any idea how best to do this?

2022-01-31 10:28 UTC, jl-wynen commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
There already is a log call in `load`...

2022-01-31 11:03 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
I would have thought just logging the name of the file would be enough

2022-01-31 11:06 UTC, nvaytet commented on src/ess/logging.py
> +                       display: bool = running_in_jupyter(),
In this case it might not slow down very much, but I think we should not encourage this practise because soon you'll find people trying to run long python functions or entire workflows as a default parameter... which could really slow down the `import`.

2022-01-31 12:09 UTC, jl-wynen commented on src/ess/logging.py
> +                       display: bool = running_in_jupyter(),
Agree

2022-01-31 12:11 UTC, jl-wynen commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
Maybe. The names I have seen so far are pretty cryptic and don't tell you what the file actually contains.

2022-02-01 08:41 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
The notebook itself should be describing what the file contains, no?

2022-02-01 09:28 UTC, jl-wynen commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading primary data file')\n",
Sure. But correlating logs with a notebook can be tricky.
I'll remove this log call but we should have something similar somewhere.

2022-02-01 12:16 UTC, nvaytet commented on docs/instruments/amor/amor_reduction.ipynb
> +    "logger.info('Loading reference file for normalization')\n",
I would also remove this logging, for the same reason as for the sample measurement.

2022-02-01 12:53 UTC, nvaytet approved these changes

2022-02-01 12:53 UTC, merged